### ISSUE TITLE
fix: source map sources names

### ISSUE THREAD

**Issue by sprat** [webpack-contrib/extract-text-webpack-plugin#258] opened 2016-09-29 21:01 UTC
I want to generate an external CSS file with a source map when I build my application, so I use the following Webpack configuration, as documented in the README:

``` javascript
var srcDir = __dirname + '/src/';
var distDir = __dirname + '/dist/';
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('[name].css');

module.exports = {
    context: srcDir,
    entry: {
        'nany': './index.js',
    },
    devtool: 'source-map',
    output: {
        path: distDir,
        filename: '[name].js',
        library: 'Nany',
        libraryTarget: 'umd'
        //devtoolModuleFilenameTemplate: '[resource-path]'  // remove webpack:/// prefix
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: extractCSS.extract('css-loader?sourceMap') }
        ]
    },
    plugins: [
        extractCSS
    ]
};
```

However, the `sources` names are not generated properly in the `.map` file: they are formatted  as `webpack:///webpack:///dashboard.css`, which is a bit strange.

I've tried to understand what's going on, but I'm a bit lost.

The `css-loader` issues a `sourceRoot` with value `webpack://` which is probably a part of the cause. But it's not necessarily bad if there's no other loader consuming the output of `css-loader`, not sure.

Then, the different source maps are assembled with `webpack-sources` helpers. If I print `source.map()` after `renderExtractedChunk`, the sources are formatted as  `webpack:///dashboard.css`

But, I guess webpack is probably adding another `webpack:///` prefix due to the `devtoolModuleFilenameTemplate` config, but I don't understand how it is achieved after the previous operation.

I'm sure sure how the problem could be solved. Maybe we should file a bug/feature request to the `css-loader` project in order to allow another `sourceRoot`? Maybe there's another way to assemble the source maps in the Extract text plugin to avoid the problem? Maybe the bug is in `webpack-sources` helpers? Any idea?

**Comment by sprat** [comment] 2016-09-29 21:19
Sorry, forgot to mention the version of the tools:
    "css-loader": "0.25.0",
    "extract-text-webpack-plugin": "1.0.1",
    "webpack": "1.13.2"

**Comment by sprat** [comment] 2016-09-29 21:33
Relevent issue in ``css-loader``: https://github.com/webpack/css-loader/issues/280

**Comment by scottdj92** [comment] 2017-02-21 21:22
Closing due to old webpack version. If your issue persists, feel free to re-open.

**Comment by brokenmass** [comment] 2017-02-24 16:15
i still have the same issue with webpack2

**Comment by scottdj92** [comment] 2017-02-24 16:31
Are you seeing this with the most recent version of this plugin?

**Comment by brokenmass** [comment] 2017-02-24 17:26
Hi @scottdj92.
Yes I'm using the most recent version of the plugin.
relevant webpack config is
```
{
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    loader: [
      {
        loader: 'css-loader',
        options: {
          importLoaders: 1,
          localIdentName: '[local]--[hash:base64:5]',
          modules: true,
          sourceMap: true
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins () {
            return [
              autoprefixer({
                browsers: [
                  '> 1%',
                  'last 3 versions',
                  'iOS > 6',
                  'ie > 9',
                  'not ie < 10'
                ]
              })
            ];
          }
        }
      },
      'sass-loader?sourceMap'
    ]
  })
}
```

sourceMap sources path are in the form `"webpack:///webpack:///~/bla/bla/bla/file.scss"`.

Anyway it looks like the problem is still caused by css-loader that force a 'wrong' sourceRoot. 

I created a PR there https://github.com/webpack-contrib/css-loader/pull/429 to 'fix' or at least mitigate the issue using an additional config parama

**Comment by evilebottnawi** [comment] 2018-02-01 14:53
Fixed https://github.com/webpack-contrib/css-loader/pull/430. Feel free to feedback and reopen if problem still exists. Thanks!

**Closed by evilebottnawi** 2018-02-01 14:53 UTC
Labels: type: Bug
