### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by maxlibin** [webpack-contrib/extract-text-webpack-plugin#354] opened 2017-01-25 11:40 UTC
trying to get extract-text-webpack-plugin to work, but seems not outputing any file here.

```
const path = require('path');
// const SSHWebpack = require('ssh-webpack-plugin');
const webpack = require('webpack');

const resolveApp = function resolveApp(relativePath) {
  return path.resolve(__dirname, relativePath);
};

const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  // You may want 'eval' instead if you prefer to see the compiled output in DevTools.
  // See the discussion in https://github.com/facebookincubator/create-react-app/issues/343.
  devtool: 'cheap-module-source-map',
  entry: [
    // We ship a few polyfills by default:
    "webpack/hot/dev-server",
    path.join(__dirname, './src', '/index.js'),
  ],
  output: { // output folder
    // path: path.resolve('dist'), // folder path
    // filename: 'crawl-incl-react.bundle.js',  // file name
    path: path.resolve(__dirname, 'dist'),
    filename: 'crawl-incl-react.bundle.js',
  },
  resolve: {
    // This allows you to set a fallback for where Webpack should look for modules.
    // We read `NODE_PATH` environment variable in `paths.js` and pass paths here.
    // We use `fallback` instead of `root` because we want `node_modules` to "win"
    // if there any conflicts. This matches Node resolution mechanism.
    // https://github.com/facebookincubator/create-react-app/issues/253
    fallback: path.resolve('../node_modules'),
    // These are the reasonable defaults supported by the Node ecosystem.
    // We also include JSX as a common component filename extension to support
    // some tools, although we do not recommend using it, see:
    // https://github.com/facebookincubator/create-react-app/issues/290
    extensions: ['.js', '.json', '.jsx', ''],
    alias: {
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
  },
  module: {
    loaders: [{
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        include: path.resolve('src'),
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          presets: ['react', 'es2015', 'stage-0'],
        },
      },
      { test: /\.json$/, loader: 'json' },
      // { test: /\.css$/, loader: 'style!css' }
      // { test: /\.css$/, loaders: [
      //   'style-loader',
      //   'css-loader?importLoaders=1',
      //   'postcss-loader'
      // ] },
      // { test: /\.css$/, loader: ExtractTextPlugin.extract('style', 'css-loader!postcss-loader') }
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("style-loader", "css-loader")
      }
    ],
  },
  plugins: [
    // new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin('css/app.css')
  ],
  stats: { colors: true },
  devServer:{
    historyApiFallback: true,
    contentBase: path.resolve('dist'),
    hot: true,
    stats: {
      chunkModules: false,
      colors: true
    }
  }
};
const path = require('path');
// const SSHWebpack = require('ssh-webpack-plugin');
const webpack = require('webpack');

const resolveApp = function resolveApp(relativePath) {
  return path.resolve(__dirname, relativePath);
};

const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  // You may want 'eval' instead if you prefer to see the compiled output in DevTools.
  // See the discussion in https://github.com/facebookincubator/create-react-app/issues/343.
  devtool: 'cheap-module-source-map',
  entry: [
    // We ship a few polyfills by default:
    "webpack/hot/dev-server",
    path.join(__dirname, './src', '/index.js'),
  ],
  output: { // output folder
    // path: path.resolve('dist'), // folder path
    // filename: 'crawl-incl-react.bundle.js',  // file name
    path: path.resolve(__dirname, 'dist'),
    filename: 'crawl-incl-react.bundle.js',
  },
  resolve: {
    // This allows you to set a fallback for where Webpack should look for modules.
    // We read `NODE_PATH` environment variable in `paths.js` and pass paths here.
    // We use `fallback` instead of `root` because we want `node_modules` to "win"
    // if there any conflicts. This matches Node resolution mechanism.
    // https://github.com/facebookincubator/create-react-app/issues/253
    fallback: path.resolve('../node_modules'),
    // These are the reasonable defaults supported by the Node ecosystem.
    // We also include JSX as a common component filename extension to support
    // some tools, although we do not recommend using it, see:
    // https://github.com/facebookincubator/create-react-app/issues/290
    extensions: ['.js', '.json', '.jsx', ''],
    alias: {
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
  },
  module: {
    loaders: [{
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        include: path.resolve('src'),
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          presets: ['react', 'es2015', 'stage-0'],
        },
      },
      { test: /\.json$/, loader: 'json' },
      // { test: /\.css$/, loader: 'style!css' }
      // { test: /\.css$/, loaders: [
      //   'style-loader',
      //   'css-loader?importLoaders=1',
      //   'postcss-loader'
      // ] },
      // { test: /\.css$/, loader: ExtractTextPlugin.extract('style', 'css-loader!postcss-loader') }
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("style-loader", "css-loader")
      }
    ],
  },
  plugins: [
    // new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin('css/app.css')
  ],
  stats: { colors: true },
  devServer:{
    historyApiFallback: true,
    contentBase: path.resolve('dist'),
    hot: true,
    stats: {
      chunkModules: false,
      colors: true
    }
  }
};
```

**Comment by bebraw** [comment] 2017-01-25 14:59
Which version of the plugin are you using? The API changed between 1 and 2.

**Comment by medigvijay** [comment] 2017-01-26 12:21
I am having the same problem and I am using the following `^2.0.0-rc.0`

**Comment by bebraw** [comment] 2017-01-26 12:22
@medigvijay Could you set up a small standalone example to show the issue? That way we can debug it.

**Comment by medigvijay** [comment] 2017-01-26 12:26
Below is my complete setup:`var webpack = require("webpack");
var path = require('path');

var ExtractTextPlugin = require('extract-text-webpack-plugin');


const DIST_DIR = path.resolve(__dirname, "dist");
const SRC_DIR = path.resolve(__dirname, "src");

const extractCSS = new ExtractTextPlugin("app.bundle.css");

var config = {
	entry: SRC_DIR + "/app/index.js",
	output: {
		path: DIST_DIR + "/app",
		filename: "bundle.js",
		publicPath: "/app/"
	},
	module: {
		rules: [
			{
				test: /\.jsx$/,
				include: SRC_DIR,
				exclude: /(node_modules)/,
				use: [
					{
						loader: 'babel-loader',
						options: {
							presets: ['react', 'es2015']
						}
					}
				]
			},
			{
				test: /\.scss$/,
				include: SRC_DIR,
				exclude: /(node_modules)/,
				loader: ExtractTextPlugin.extract({
			      fallbackLoader: "style-loader",
			      loader: "sass-loader",
			      publicPath: "/dist"
			    })
			}
		]
	},
	plugins: [
		extractCSS
	]
};

module.exports = config`

**Comment by bebraw** [comment] 2017-01-26 12:31
@medigvijay I don't see anything obviously wrong there. I would need a GitHub repository to say anything concrete.

**Comment by medigvijay** [comment] 2017-01-26 12:33
@bebraw : Exactly. The configuration is fine and the `js` bundle does get generated but not the extracted CSS.

**Comment by bebraw** [comment] 2017-01-28 05:49
Can you try `use: ExtractTextPlugin`?

**Comment by medigvijay** [comment] 2017-01-28 06:18
Tried that, but no luck

**Comment by bebraw** [comment] 2017-01-28 06:22
Ok. Can you set up a GitHub project? Easier to debug.

**Comment by medigvijay** [comment] 2017-01-28 06:32
Did that [here](https://github.com/medigvijay/webpack-issue).

**Comment by bebraw** [comment] 2017-01-28 07:42
@medigvijay The problem is that there's nothing to extract. It never gets to the plugin logic for that reason. Here are the changes I had to make to fix it:

```diff
diff --git a/package.json b/package.json
index 1f0c963..610a921 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
   "scripts": {
     "start": "npm run build",
     "build": "webpack -d && copy src\\index.html dist\\index.html && webpack-dev-server --content-base src --inline --hot",
-    "build:prod": "webpack -p && copy src\\index.html dist\\index.html"
+    "build:prod": "webpack -p"
   },
   "dependencies": {
     "history": "^4.5.1",
diff --git a/src/app/index.js b/src/app/index.js
index bf6e990..2dff56d 100644
--- a/src/app/index.js
+++ b/src/app/index.js
@@ -1 +1,3 @@
+import './main-src.scss';
+
 console.log("Yayyyyyyyyy");
\ No newline at end of file
diff --git a/webpack.config.js b/webpack.config.js
index 6f1974e..be0e8f6 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -17,7 +17,7 @@ var config = {
 		publicPath: "/app/"
 	},
 	module: {
-		loaders: [
+		rules: [
 			{
 				test: /\.jsx$/,
 				include: SRC_DIR,
@@ -35,9 +35,9 @@ var config = {
 				test: /\.scss$/,
 				include: SRC_DIR,
 				exclude: /(node_modules)/,
-				loader: ExtractTextPlugin.extract({
+				use: ExtractTextPlugin.extract({
 			      fallbackLoader: "style-loader",
-			      loader: "sass-loader",
+			      loader: ["css-loader", "sass-loader"],
 			      publicPath: "/dist"
 			    })
 			}
```

You might want to replace `copy` with `cpy` or so, but that's enough to illustrate the idea.

**Comment by bebraw** [comment] 2017-01-28 07:43
@maxlibin I could use a standalone example from you too.

**Comment by medigvijay** [comment] 2017-01-28 08:59
The main difference here I can see is the import statement in index.js.
`import './main-src.scss';`
I am not sure if I want to include the file in the js file. Can I include the compiled css into one of my html files?

**Comment by bebraw** [comment] 2017-01-28 09:01
@medigvijay You have to refer to the styling files somewhere (js, entries, etc.). Otherwise the plugin cannot work as there's nothing to extract.

**Comment by maxlibin** [comment] 2017-01-31 10:59
I am using webpack 1

**Comment by bebraw** [comment] 2017-01-31 11:11
@maxlibin Any chance you could update to webpack 2? I would need a standalone project to say anything concrete. Make sure your code points to the CSS to extract as otherwise it won't pick it up.

**Comment by willdembinski** [comment] 2017-02-10 21:57
Im encountering this issue and its totally maddening.  What to do to fix?

**Comment by willdembinski** [comment] 2017-02-10 21:58
Pleasssse help:
```
var path                     = require('path');
var webpack                  = require('webpack');
var NODE_MODULES_PATH        = path.resolve(__dirname, 'node_modules');
var CircularDependencyPlugin = require('circular-dependency-plugin');
var BUILD_PATH               = path.resolve(__dirname, 'dist');
var MAIN_PATH                = path.resolve(__dirname, 'src','client','index.js'); //The root of the actual application
var ExtractTextPlugin        = require('extract-text-webpack-plugin');

module.exports = {
    devtool:'inline-source-map',
    entry: [
        'whatwg-fetch',
        MAIN_PATH
    ],
    output: {
        path:BUILD_PATH,
        publicPath:'/', //This actually doesnt "exist". But the webpack server (and hopefully middleware) will serve files when hit at that endpoint
        filename: 'bundle.js'
    },
    module: {
      rules: [
        {
            test: /\.js$/,
            use: ['babel'],
            query:{
              presets:['react',"es2015","stage2"]
            },
            include: path.join(__dirname, 'src'),
            exclude:[NODE_MODULES_PATH]
        },
        {
            test: /\.scss$/,
            exclude:path(__dirname,'node_modules'),
            use: ExtractTextPlugin.extract({
              fallback: "style-loader",
              use: "css-loader!sass-loader",
          })
        }
      ]
    },
    resolve: {
        alias: {
           Root:                           __dirname
           ,Themes:                        __dirname + '/src/client/themes'
           ,Middleware:                    __dirname + '/src/client/middleware'
           ,src:                           __dirname + '/src/client' //I think we should change this just to "Client"
           ,components:                    __dirname + '/src/client/components'
           ,SettingsComponents:            __dirname + '/src/client/components/SettingsComponents'
           ,SettingsTypes:                 __dirname + '/src/client/components/SettingsComponents/Types'
           ,actions:                       __dirname + '/src/client/actions'
           ,containers:                    __dirname + '/src/client/containers'
           ,reducers:                      __dirname + '/src/client/reducers'
           ,modules:                       __dirname + '/src/client/modules'
           ,constants:                     __dirname + '/src/constants'
           ,copyHelper:                    __dirname + '/utils/copy_helper.js'
           ,requestActionItemsBoilerplate: __dirname + '/src/client/actions/requestActionItemsBoilerplate'
           ,requestBootStrapData:          __dirname + '/src/client/actions/requestBootStrapData'
        }
    },
    plugins: [
      new ExtractTextPlugin('bigtimestyles.css'),
      new webpack.NoErrorsPlugin(),
      new webpack.optimize.DedupePlugin(),
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development')
        }
      }),
      new CircularDependencyPlugin({
        exclude:(/node_modules/i),
        failOnError: true
      })
    ]
};
```

**Comment by michael-ciniawsky** [comment] 2017-02-10 22:36
@willdembinski 

`extract-text-webpack-plugin` >= `v2.0.0-rc.3` ? 😛 

```diff
- use: "css-loader!sass-loader",
+ use: [
+   { loader: "css-loader", options: { importLoaders: 1 } },
+   "sass-loader" // { loader: "sass-loader", options: { includePaths: '...' } } => if @import 
+ ]
```

Otherwise take a close look at your resolve aliases 🙃

**Comment by michael-ciniawsky** [comment] 2017-02-10 22:38
@willdembinski 

```diff
- use: ['babel']
+ use: ['babel-loader']
```

**Comment by willdembinski** [comment] 2017-02-10 22:53
@michael-ciniawsky - A: Thank you so much for the help!

`"sass-loader" // { loader: "sass-loader", options: { includePaths: '...' } }` <- That is amazing.

I now have this:
```
    module: {
      rules: [
        {
            test: /\.s?css$/,
            // exclude:path.join(__dirname,'node_modules'),
            use: ExtractTextPlugin.extract({
              fallback: "style-loader",
              // use: "css-loader!sass-loader",
              use: [
                { loader: "css-loader", options: { importLoaders: 1 } },
                { loader: "sass-loader", options: { includePaths: './themes' }}
              ]

          })
        },
        {
            test: /\.js$/,
            use: ['babel-loader'],
            query:{
              presets:['es2015','react','stage2']
            },
            include: path.join(__dirname, 'src'),
            exclude:[NODE_MODULES_PATH]
        }
      ]
    },
```
Thank you for that. I now have this issue where its failing to build *all* of the files.  It seemingly stops after a handful.  You wouldnt have any magical awesome knowledge about that would you? :smile: :heart:

**Comment by willdembinski** [comment] 2017-02-10 23:19
Alright - I figured it out.  This thing will fail silently.  It will compile the file to the best of its ability, but if it encounters: a mixin, a sass variable, whatever - that it can't interpret - it just shits the bed and prints what it can.

**Comment by bebraw** [comment] 2017-02-19 16:35
@maxlibin Any chance for a project to study?

**Comment by michael-ciniawsky** [comment] 2017-02-19 20:45
@medigvijay 

```diff
module: {
  rules: [
    {
       test: /\.scss$/,
       include: SRC_DIR,
       exclude: /(node_modules)/,
-     loader: ExtractTextPlugin.extract({
+     use: extractCSS.extract({ // you need to use your Instance* here :)
-       fallbackLoader: 'style-loader',
+       fallback: "style-loader",
-       loader: "sass-loader",
+       use: [ 
+           { loader: "css-loader" options: { importLoaders: 1 } }, // css-loader is mandatory
+           { loader: "sass-loader"  options: { includePaths: 'path/to/@imports'} // if @import
+        ],
         publicPath: "/dist"
       })
      }
    ]
  },
  plugins: [
    extractCSS  // <= *        
  ]
```

**Comment by michael-ciniawsky** [comment] 2017-02-19 20:49
@maxlibin 

```diff
{
   test: /\.css$/,
-   loader: ExtractTextPlugin.extract("style-loader", "css-loader")
+  use: ExtractTextPlugin.extract({
         fallback: 'style-loader',
         use: [ 'css-loader' ]
     })
}
```

**Comment by bebraw** [comment] 2017-02-20 03:57
Please re-open with a project to study if that won't fix.

**Closed by bebraw** 2017-02-20 03:57 UTC
Labels: bug, needs-more-information, webpack-2
