### ISSUE TITLE
2.0.0-rc.0 not removing css from bundles

### ISSUE THREAD

**Issue by phun-ky** [webpack-contrib/extract-text-webpack-plugin#366] opened 2017-01-27 13:54 UTC
with this config: https://gist.github.com/phun-ky/34744023578f6f000f0de427f11d3800

I am getting bundles with loads of duplicate css in them, like this screenshot: 
![screenshot from 2017-01-27 14-45-06](https://cloud.githubusercontent.com/assets/1714029/22373091/8168f4e0-e4a0-11e6-8832-6a8ea6743ab4.png)

I get the correct css files produced, but the styles are still in the bundles

**Comment by bebraw** [comment] 2017-01-27 18:37
Can you see the same in earlier betas? Any chance for a little project to run?

**Comment by bebraw** [comment] 2017-01-28 05:46
Can you try `use: extractTextPlugin.extract`? Only the new style is supported now.

**Comment by bebraw** [comment] 2017-01-31 12:18
The old style (` loader: extractTextPlugin.extract`) should work too as webpack core supports the legacy format (tried it out). I would need a standalone project to do anything about this issue. This is blocking the release at the moment.

**Comment by bebraw** [comment] 2017-02-04 09:09
@phun-ky Can you set up a standalone example? This is one of the final issues blocking a release.

**Comment by phun-ky** [comment] 2017-02-06 08:34
Sorry for the late reply! Sure thing! Will do later tonight, at work
atm.

---
ALEXANDER VASSBOTN RØYNE-HELGESEN
Lover of life, technologist at heart
+47 997 98 910 

alexander@phun-ky.net | http://phun-ky.net |
https://no.linkedin.com/in/alexanderroyne  

TVETERVEIEN 33B 
1344 HASLUM 
NORWAY

The content of this email is confidential and intended only for the
person to whom it is addressed. If you are not the intended recipient,
disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited. Please notify
the sender immediately, and delete the content, if you have received
this email by mistake. 

Den 2017-02-04 10:09, skrev Juho Vepsäläinen:

> @phun-ky [1] Can you set up a standalone example? This is one of the final issues blocking a release. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/phun-ky
[2]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/366#issuecomment-277430489
[3]

**Comment by csonlai** [comment] 2017-02-06 14:48
I meet the same problem when using webpack2

**Comment by bebraw** [comment] 2017-02-06 14:54
@csonlai I'm still waiting for an example. No way to fix unless someone provides one.

**Comment by phun-ky** [comment] 2017-02-06 20:23
https://github.com/phun-ky/webpack-2-extract-text-plugin-example

here it is. It occured to me, that if this is run with `webpack -p`, no css is in the `/assets/app.js` file, but with `webpack`, I get the css in the file.

I will have to research a bit more, because I reported this issue with webpack run programatically, not via cli, with `process.NODE_ENV=production`

**Comment by bebraw** [comment] 2017-02-07 14:53
@phun-ky I get `/assets/app.css` with and without `-p`. It's the same output. Why would you expect to see CSS in `/assets/app.js`?

**Comment by bebraw** [comment] 2017-02-07 14:56
Anyway, I can't repro the behavior (probably missing some step you did).

It would be good if someone else could it give a go.

**Comment by phun-ky** [comment] 2017-02-15 13:46
@bebraw I don't expect to see CSS in `/assets/app.js` or any of my bundles, that's the point

**Comment by bebraw** [comment] 2017-02-15 15:27
@phun-ky I did not see that behavior myself.

**Comment by hulkish** [comment] 2017-02-16 03:15
I'm seeing this issue

**Comment by bebraw** [comment] 2017-02-16 06:26
@hulkish Was that against the example above? Can you provide some information on your environment?

**Comment by hulkish** [comment] 2017-02-17 04:06
@bebraw I'm having issues reproducing this again. However, I am still using same version of everything. I will report again if I see it again.

**Comment by hulkish** [comment] 2017-02-23 02:30
Yea, I'm definitely still seeing this issue in rc.3. However, I am having difficulty nailing down the cause.

**Comment by hulkish** [comment] 2017-02-23 13:53
so,  ive tried everything in order to get to the bottom of this one.  If anyone ekse xan provide some insight that'd be really helpful.

**Comment by scottdj92** [comment] 2017-02-23 13:58
@hulkish can you share your repo?

**Comment by hulkish** [comment] 2017-02-23 14:04
@scottdj92, it seems to occur when trying to use completely webpack 2 syntax of `use`,  instead of `loaders`,  and / or `options` instead of `query`

**Comment by hulkish** [comment] 2017-02-23 14:09
ibe tried several versions of: sass-loader,  postcss-loader,  css-loader,  style-loader & extract-text-webpack-plugin...  it didn't affect my result..  but adding webpack 2 syntax def broke it

**Comment by scottdj92** [comment] 2017-02-23 14:12
Can you share your repo and webpack config?

**Comment by hulkish** [comment] 2017-02-23 14:14
i can't due to proprietary reasons..  but i will try to recreate tge issue in  a new repo and share here

**Comment by hulkish** [comment] 2017-02-23 14:31
perhaps my approach is incorrect..  is the following the intended loader syntax for `extract-text-webpack-plugin@2.0.0-rc.3`?

```
{
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: { loader: 'style-loader',  options: { sourceMap: true }, 
          use: [
            { loader: 'css-loader',  options: { sourceMap: true }, 
            { loader: 'postcss-loader',  options: { sourceMap: true }, 
          { loader: 'sass-loader',  options: { sourceMap: true },
         ] 
        ]) 
      } 
    ] 
  } 
} 
```

**Comment by bebraw** [comment] 2017-02-23 14:35
@hulkish You are missing a brace after `fallback: { loader: 'style-loader',  options: { sourceMap: true },`. Could that be it?

There really is no way we could help without a small test case to study.

**Comment by hulkish** [comment] 2017-02-23 14:40
@bebraw no...  thats just my fat thumbs because i wrote it on my phone (i give you permission to point and laugh),  just wanted to give a quick idea of what im trying to do

**Comment by hulkish** [comment] 2017-02-23 15:27
@bebraw can you at least confirm that my snippet above is the correct intended usage?

**Comment by scottdj92** [comment] 2017-02-23 15:32
It looks right to me, if you follow with what @bebraw mentioned.

**Comment by hulkish** [comment] 2017-02-27 20:40
I **finally** determined the cause...can you spot it?
```js
  plugins: [
    new ExtractTextPlugin({
      filename: '[name].[hash].js',
      allChunks: true,
      disable
    })
  ]
```
This should have been far more obvious on my part, still don't know how I missed it. Anyway - hopefully my headbutting at least benefits someone else... double triple check your webpack config, folks!

**Comment by scottdj92** [comment] 2017-02-27 20:52
Please explain what you fixed, for posterity. Afterwards if there's no other issues, I can close this up! 😄

**Comment by hulkish** [comment] 2017-02-27 20:55
`[name].[hash].js` => `[name].[hash].css`...... walk of shame

**Comment by scottdj92** [comment] 2017-02-27 20:57
It happens to the best of us.

**Closed by scottdj92** 2017-02-27 20:57 UTC
Labels: needs-more-information, webpack-2
