### ISSUE TITLE
refactor: handle errors correctly

### ISSUE THREAD

**Issue by romeovs** [webpack-contrib/extract-text-webpack-plugin#113] opened 2015-10-07 14:11 UTC
When I'm using `extract-text-webpack-plugin`, errors thrown by linters (`stylint-loader` for example), are made way more verbose than they should be and show up double for some reason. Is there a way to tune this behaviour?

Check out the MWE at https://gist.github.com/romeovs/0116b8c54e8167546dc6. 

Without `extract-text-webpack-plugin` the error is clean:

```
$ webpack
Hash: 88483c7f60b32c05aa40
Version: webpack 1.12.2
Time: 936ms
      Asset     Size  Chunks             Chunk Names
    main.js  11.1 kB       0  [emitted]  main
main.js.map  14.5 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
   [1] ./client.js 38 bytes {0} [built]
    + 4 hidden modules

ERROR in ./~/css-loader!./~/stylus-loader!./~/stylint-loader?{"reporter":"stylint-stylish","semicolons":{"expect":"never","error":true}}!./error.styl



error.styl
  line 3:  unecessary semicolon found

  ✖  1 error
```

with `extract-text-webpack-plugin` it is overly complicated:

```
Hash: 57d01db00c6c03f278b2
Version: webpack 1.12.2
Time: 918ms
      Asset     Size  Chunks             Chunk Names
    main.js   9.8 kB       0  [emitted]  main
main.js.map  11.9 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
   [1] ./client.js 38 bytes {0} [built]
    + 3 hidden modules

ERROR in ./~/extract-text-webpack-plugin/loader.js!./~/css-loader!./~/stylus-loader!./~/stylint-loader?{"reporter":"stylint-stylish","semicolons":{"expect":"never","error":true}}!./error.styl
Module build failed: ModuleError: 


error.styl
  line 3:  unecessary semicolon found

  ✖  1 error

    at DependenciesBlock.<anonymous> (/Users/romeovs/web/examples/error/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:79:21)
    at Object.stylint.methods.done (/Users/romeovs/web/examples/error/node_modules/stylint-loader/index.js:28:15)
    at Object.doneHandler (/Users/romeovs/web/examples/error/node_modules/stylint-stylish/index.js:99:15)
    at Object.exports.default [as reporter] (/Users/romeovs/web/examples/error/node_modules/stylint-stylish/index.js:104:24)
    at Object.<anonymous> (/Users/romeovs/web/examples/error/node_modules/stylint/src/core/parse.js:44:16)
    at Array.forEach (native)
    at Object.parse (/Users/romeovs/web/examples/error/node_modules/stylint/src/core/parse.js:17:13)
    at Object.stylint.methods.read (/Users/romeovs/web/examples/error/node_modules/stylint-loader/index.js:12:14)
    at Object.init (/Users/romeovs/web/examples/error/node_modules/stylint/src/core/init.js:45:14)
    at /Users/romeovs/web/examples/error/node_modules/stylint/node_modules/stampit/stampit.js:88:25
    at forEach (/Users/romeovs/web/examples/error/node_modules/stylint/node_modules/stampit/node_modules/mout/array/forEach.js:15:27)
    at Function.factory (/Users/romeovs/web/examples/error/node_modules/stylint/node_modules/stampit/stampit.js:86:7)
    at lint (/Users/romeovs/web/examples/error/node_modules/stylint-loader/index.js:47:6)
    at Object.module.exports (/Users/romeovs/web/examples/error/node_modules/stylint-loader/index.js:71:5)
 @ ./error.styl 4:14-292
Child extract-text-webpack-plugin:
        + 2 hidden modules

    ERROR in ./~/css-loader!./~/stylus-loader!./~/stylint-loader?{"reporter":"stylint-stylish","semicolons":{"expect":"never","error":true}}!./error.styl



    error.styl
      line 3:  unecessary semicolon found

      ✖  1 error
```

**Comment by lukasgeiter** [comment] 2015-12-15 13:29
I'm having a very similar issue. In my case however the error doesn't just show up twice but about 15 times (I believe the number depends on how many files/modules the plugin runs through). Also this probably happens regardless what loader the error comes from as I'm having the problem with the `awesome-typescript-loader`.

**Comment by lukasgeiter** [comment] 2015-12-15 13:57
I've identified the piece of code that causes this issue. It's [Line in 246-250 index.js](https://github.com/webpack/extract-text-webpack-plugin/blob/master/index.js#L246-L250). When an error occurs during the module rebuild, the error is pushed to `compilation.errors` and therefore displayed in the output.

**Comment by scottdj92** [comment] 2017-01-29 15:10
What would be the use case for this? Would people prefer a single error to be printed out, rather than a large chunk? What happens if there's duplicate errors in multiple files?

**Comment by lukasgeiter** [comment] 2017-01-30 20:25
@scottdj92 Interestingly enough this is actually not a problem for me anymore. I can't say whether it was an update (of webpack or this loader) or if a change I made in my configuration fixed it.
I'm not the OP, but if it were up to me, this issue can be closed.

**Comment by scottdj92** [comment] 2017-01-30 20:58
@lukasgeiter can you share what version of webpack and ExtractTextPlugin you're using?

I agree, I'd wait for @romeovs to report back before closing.

**Comment by lukasgeiter** [comment] 2017-01-30 21:04
@scottdj92 Sure.
webpack: 1.13.0
extract-text-webpack-plugin: 0.9.1

**Comment by evilebottnawi** [comment] 2017-08-18 09:58
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2017-08-18 09:58 UTC
Labels: type: Refactor
