### ISSUE TITLE
[4.0.0-alpha.0] Cannot read property 'requestShortener' of undefined

### ISSUE THREAD

**Issue by machineloop** [webpack-contrib/extract-text-webpack-plugin#722] opened 2018-02-17 14:10 UTC
Using 4.0.0-alpha.0, Webpack 4.0.0-beta.1, Node 9.3.0 on macOS 10.12.6:

Thanks for the hard work on this! Thought I'd try out the new Alpha.0 with my build, looks like I may have found a bug. I'm getting the following error that clearly shows extract-text-webpack-plugin in the stack trace:

```
Fatal error: Cannot read property 'requestShortener' of undefined
TypeError: Cannot read property 'requestShortener' of undefined
    at ConcatenatedModule.source (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/optimize/ConcatenatedModule.js:370:44)
    at Function.renderExtractedChunk (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:298:46)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:286:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:846:32)
    at _err0 (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _async2.default.forEach.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:281:11)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1050:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:259:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1050:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:253:20)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at _async2.default.forEach (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:214:27)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at compilation.hooks.optimizeTree.tapAsync (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:208:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:789:27)
    at hooks.make.callAsync.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compiler.js:446:17)
    at _done (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err332 (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:4004:22)
    at _addModuleChain (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:672:11)
    at processModuleDependencies.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:614:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Task 'webpack:production' took 38925ms
```

Not sure what the best way is to create a minimal project showing issue. Happy to follow-up with more info... Thanks!

**Comment by michael-ciniawsky** [comment] 2018-02-17 17:47
For reference https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L370

**Comment by TheLarkInn** [comment] 2018-02-20 17:32
Do you think you could reduce this to a minimal reproduction in a repository? This would help us significantly solve this.

**Comment by circlingthesun** [comment] 2018-02-25 14:24
Well, it's calling `chunkModule.source()` (here: https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v4.0.0-alpha.0/src/index.js#L94) without any parameters (see: https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L437)

**Comment by phaistonian** [comment] 2018-02-26 09:07
The visual way - in case it helps any more.

![image](https://user-images.githubusercontent.com/796530/36661824-27cacd2e-1ae5-11e8-9508-d1478644d63f.png)

**Comment by peter-mouland** [comment] 2018-02-26 21:07
I can reproduce this by turning my webpack config from `development` mode to `production` (i.e. no error when in dev).

I also noticed my old code had:

`System.import('./app/utils/analytics').then((analytics) => analytics.init());`

Please correct me if I am wrong, but I think `system.import` is deprecated and we should now be using `import()`.  anyway, I commented out the offending line and everything is now dandy.

Hope this helps.

**Comment by peter-mouland** [comment] 2018-02-26 21:26
# test case

```js
// src/entry.js
try {
  System.import('./app/utils/analytics').then((analytics) => analytics.init());
} catch (err) {
  console.log('Render error', err);
}
```

```js
// webpack.config.js
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const prodConfig = {
  mode: 'production',
  entry: {
    app: ['./src/entry.js']
  },
  output: {
    path: '/Users/petermouland/dev/personal/react-ssr-base/compiled/dist',
    filename: '[name]-[hash].js',
    publicPath: '/'
  },
  plugins: [
    new ExtractTextPlugin('[name].css'),
  ],
};

module.exports = prodConfig;

```

The above give an the error.  The error can be resolved by either:
 * remove the use of `System.import` from entry.js 
 * remove the use of `new ExtractTextPlugin('[name].css'),` from webpack config

**Comment by circlingthesun** [comment] 2018-02-26 21:42
I'm not using System.import (at least not directly) and I'm still experiencing this issue.

**Comment by circlingthesun** [comment] 2018-02-26 21:42
I'm not using System.import (at least not directly) and I'm still experiencing this issue.

**Comment by peter-mouland** [comment] 2018-02-26 21:47
are you using `ExtractTextPlugin`? 
do you think you could try to reproduce a minimal test case as I've done above to help narrow down your problem code?

**Comment by circlingthesun** [comment] 2018-02-26 23:29
@peter-mouland I tried to reproduce it with a minimal example, but have not been able to. I can't even make it choke on `System.import`.

**Comment by DNLHC** [comment] 2018-02-27 00:03
It seems like it breaks with any dynamic imports not just `System.import`
I have several dynamic imports
`const Contacts = () => import('./contacts' /* webpackChunkName: "contacts" */);`
after changing it to
`import Contacts from './contacts';`
everything builds fine

**Comment by AndyBarron** [comment] 2018-02-27 07:37
Confirming the above comment - changing ES async imports to standard ES imports fixes this.

**Comment by AndyBarron** [comment] 2018-02-27 07:40
Additionally, I can confirm that removing `extract-text-webpack-plugin` from my `webpack.config.js` fixes the issue.

**Comment by circlingthesun** [comment] 2018-02-27 23:07
@TheLarkInn I've systematically hollowed out a project and ended up with this minimal reproduction: https://github.com/circlingthesun/extract-text-webpack-plugin-bug

**Comment by michael-ciniawsky** [comment] 2018-02-28 02:58
Released in [v4.0.0-beta.0](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v4.0.0-beta.0) 🎉

**Comment by peter-mouland** [comment] 2018-02-28 08:52
that commit looks like it should do the job 👍 I'll be able to test when i get back from work.  thanks @michael-ciniawsky! 

@circlingthesun looking at your reduced test case, your problem is the same as previously mentioned (i.e. dynamic imports) so you should be good to go also 🎉

**Comment by circlingthesun** [comment] 2018-02-28 08:57
@peter-mouland looks like it works :+1:

**Comment by evilebottnawi** [comment] 2018-02-28 09:45
Thanks everyone :+1:

**Closed by evilebottnawi** 2018-02-28 09:45 UTC
Labels: priority: 4 (important), severity: 3 (broken), type: Bug

**Comment by CinKon** [comment] 2018-03-01 14:02
I still got that bug when I use dynamic imports like this:

```
const Contacts = () => import('./contacts' /* webpackChunkName: "contacts" */);
```

as it has to be used for https://router.vuejs.org/en/advanced/lazy-loading.html

**Comment by CinKon** [comment] 2018-03-01 14:08
Sorry, missed the beta-release
