### ISSUE TITLE
Unable to parse Sass (.scss)

### ISSUE THREAD

**Issue by wsfuller** [webpack-contrib/extract-text-webpack-plugin#424] opened 2017-02-21 22:34 UTC
Unable to get Webpack 2.2.1 to parse a .scss file

I'm not sure what's going on with these loaders. I'm following the [setup guide](https://webpack.js.org/plugins/extract-text-webpack-plugin/) and getting module parsing errors for some reason. I can get the CSS-Loader to work but when it comes to sass the provided plugins aren't working. What am I doing wrong in this setup? 

**package.json**

    ...
    "devDependencies": {
      "css-loader": "^0.26.1",
      "extract-text-webpack-plugin": "^2.0.0-rc.3",
      "favicons-webpack-plugin": "0.0.7",
      "html-webpack-plugin": "^2.28.0",
      "node-sass": "^4.5.0",
      "sass-loader": "^6.0.2",
      "style-loader": "^0.13.1",
      "webpack": "^2.2.1"
    },
    ...

**Structure:**

    /webpack-demo
      /app
        /assets
          /stylesheets
            test-style.css
            test-style.scss
        index.js

  **test-style.css:**

  `a {display: flex;}`

  **test-style.scss:**

  `a{display: flex;}`

  **index.js**

    import './assets/stylesheets/test-style.scss';
    import _ from 'lodash';

    function component () {
      var element = document.createElement('div');

      /* lodash is required for the next line to work */
      element.innerHTML = _.join(['Hello','webpack', 'what up breh'], ' ');

      return element;
    }

    document.body.appendChild(component());

**webpack.config.js**

    const path = require('path');
    let HtmlWebpackPlugin = require('html-webpack-plugin');
    let FaviconsWebpackPlugin = require('favicons-webpack-plugin');
    const ExtractTextPlugin = require("extract-text-webpack-plugin");
    module.exports = {
      entry: './app/index.js',
      output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
      },
      module: {
        rules: [{
            test: /\.scss$/,
            //use: ['style-loader', 'css-loader']
            use: ExtractTextPlugin.extract({
              fallback: "style-loader",
              //use: "css-loader"
              use: ['css-loader', 'sass-loader']
            })
        }]
      },
      plugins: [
        new HtmlWebpackPlugin(),
        new FaviconsWebpackPlugin('./app/images/me.png'),
        new ExtractTextPlugin('./assets/stylesheets/styles.css')
      ]
    };

**Errors:**

    ERROR in ./~/sass-loader/lib/loader.js!./app/assets/stylesheets/test-style.scss
    Module parse failed: /Users/steve_fuller/development/react-tutorials/webpack-demo/node_modules/sass-loader/lib/loader.js!/Users/steve_fulle
    r/development/react-tutorials/webpack-demo/app/assets/stylesheets/test-style.scss Unexpected token (1:2)
    You may need an appropriate loader to handle this file type.
    | a {
    |   display: flex; }
    |
     @ ./app/assets/stylesheets/test-style.scss 4:14-92
     @ ./app/index.js

**Comment by michael-ciniawsky** [comment] 2017-02-21 23:01
> /Users/steve_fuller/development/react-tutorials/webpack-demo/node_modules/sass-loader/lib/loader.js!/Users/steve_fulle
r/development/react-tutorials/webpack-demo/app/assets/stylesheets/test-style.scss Unexpected token (1:2)

@wsfuller Seems lika Syntax Error in `test-style.scss` missing `.` before `a` (ClassSelector)

`a {}` => `.a {}`

**Comment by michael-ciniawsky** [comment] 2017-02-21 23:04
But I wonder still, bc it should work, `sass-loader` seems to be executed nevertheless

**Comment by wsfuller** [comment] 2017-02-21 23:07
The intent was to purposely apply that to the anchor tag. I would run this through Gulp and the lib-sass compiler, the only reason is to then test autoprefixer and make that is working since the `display` property needs vendor prefixes and easy to write.

I've added:

    {
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract({
        fallback: "style-loader",
        use: "css-loader!sass-loader",
      }),
    } 

And that is working as expected. The starter documentation isn't really getting me in a good spot to start working imo. Like to troubleshoot to understand as much as the next person but the way Webpack works has been interesting to say the least.

**Comment by michael-ciniawsky** [comment] 2017-02-21 23:13
I understand :), this maybe related [SASS Loader #372](https://github.com/webpack-contrib/sass-loader/issues/372). Could you please post your issue there aswell, maybe sass-loader recently introduced a bug somwhere. Thx in advance 👍 💯

**Comment by wsfuller** [comment] 2017-02-21 23:21
You got it, posted answer on that issue.

**Comment by jsg2021** [comment] 2017-02-28 15:59
I seem to be facing this issue as well. The solution posted so far is to use the string form of stacked loaders... `"css-loader!sass-loader"`... which, reading the code gets transformed into `[{loader: 'css-loader'},{loader:'sass-loader'}]`.  I'm a little at a loss here.

```
{
    test: /\.(s?)css$/,
    use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
            {
                loader: 'css-loader',
                options: {
                    sourceMap: true
                }
            },
            {
                loader: 'postcss-loader',
                options: {
                    sourceMap: 'inline',
                    plugins: () => [
                        autoprefixer({ browsers: ['> 1% in US', 'last 2 versions', 'iOS > 8'] })
                    ]
                }
            },
            {
                loader: 'resolve-url-loader'
            },
            {
                loader: 'sass-loader',
                options: {
                    sourceMap: true
                }
            }
        ]
    })
}
```

**Comment by jsg2021** [comment] 2017-02-28 16:08
I think I miss-read the solution... was it adding an additional loader rule for `/.scss$/`? :/

**Comment by jsg2021** [comment] 2017-02-28 16:32
I'm starting to wonder if the test expression is no longer working (was in v1). The regexp matches both '.scss' and '.css'.

**Comment by wsfuller** [comment] 2017-03-01 18:20
Could very well be, know there has been a lot going on behind the scenes. I haven't read all the way through this https://github.com/webpack/webpack/issues/2797 but you can take a look through and see if it leads to any answers. The elephant in the room is to try and find a balance of low versus high level setup and trying to standardize the tool since everyone has a different spin on their configurations because the tool is so open.

**Comment by jsg2021** [comment] 2017-03-02 00:53
ah, i believe the problem is the use of the property `use: ...`. The working examples have `loader: ...`. I will have to test to verify, but i've seen other hints that this is the key.

**Comment by wsfuller** [comment] 2017-03-02 01:10
Both `use` and `loaders` should be valid syntax. Looking back over your code could you try to make loaders plural? Just want to eliminate that being a possibility as well. Watching a very good series that was crated in 02/17 that's going through some explanations. [YouTube: Webpack 2 - Style, CSS and Sass loaders](https://youtu.be/m7V0OackwxY)

**Comment by jsg2021** [comment] 2017-03-02 15:36
Based on @bebraw 's comment [here](https://github.com/webpack/webpack/issues/2797#issuecomment-234706953) on webpack/webpack#2797 , I believe my problem is the use of the plural properties (use/loaders) and needs to be the singular `loader` property.

**Comment by jsg2021** [comment] 2017-03-02 16:32
Update: my extract text config works on scss files when my js files import scss files explicitly. eg: 

```js
import './main.scss';

export default class Main ...
```

but I also have a convention pre-loader that adds imports to scss files that match component file names using the baggage-loader. eg: Button.js auto imports Button.scss. These imports are failing to go through my loader rules. :/

**Comment by jsg2021** [comment] 2017-03-02 17:26
[Found it.](https://github.com/jsg2021/baggage-loader/blob/master/index.js#L50) The baggage-loader was erroneously prefixing '!' to the require :/

**Comment by mammut89** [comment] 2017-03-05 22:49
wasted quite a bit of time on this. Having to import the scss is rather unintuitive and not mentioned in the docs

**Comment by d3viant0ne** [comment] 2017-03-06 04:17
Note to @webpack-contrib/org-maintainers - Once this has been worked out, review the documentation around the issue for clarity.

**Comment by jsg2021** [comment] 2017-03-06 05:12
I should reiterate, my issue was from an error in another loader (baggage-loader) that auto-imports files based on convention. (it was bypassing loaders for files it included by prefixing the request with "!")

When I imported sass files explicitly, things worked fine with the config i posted above.

**Comment by bebraw** [comment] 2017-03-06 06:09
@d3viant0ne It's literally one of the first sentences at the documentation: "It moves all the `require("style.css")`s in entry chunks into a separate single CSS file. So your styles are no longer inlined into the JS bundle, but separate in a CSS bundle file (`styles.css`). If your total stylesheet volume is big, it will be faster because the CSS bundle is loaded in parallel to the JS bundle.".

That said, if someone wants to clean that up, PR is welcome.

Time to close this issue.

**Closed by bebraw** 2017-03-06 06:09 UTC
Labels: bug, documentation, webpack-2

**Comment by d3viant0ne** [comment] 2017-03-06 06:45
Yeah, I just read through it. It's clear enough for me :)
