### ISSUE TITLE
Problems with WrapperPlugin

### ISSUE THREAD

**Issue by marcelalburg** [webpack-contrib/extract-text-webpack-plugin#161] opened 2016-03-13 16:58 UTC
Hello,

i'm using extract-text-webpack-plugin for my client css and it works perfectly. But when i use it for server side rending and using the plugin wrapper-webpack-plugin it fails with

```
ERROR in ../src/views/CounterView/CounterView.scss
Module build failed: TypeError: text.forEach is not a function
    at Object.<anonymous> (node_modules/extract-text-webpack-plugin/loader.js:100:11)
```

But i need to add this in my webpack config

```
webpackConfig.plugins.push(new WrapperPlugin({
    header: 'exports.vertxStartAsync = function(startFuture) {\n',
    footer: '\n\n}\n\n'
}));
```

if i remove this plugin. it works. if i change the header and footer to some comments - works too.

Is there a easy solution ? 

Thanks
Marcel

**Comment by bebraw** [comment] 2017-01-28 08:28
Can you set up a little standalone example to study?

**Comment by michael-ciniawsky** [comment] 2017-04-22 19:13
Please provide more info about your setup (`webpack.config.js`) and elaborate on the usecase fot this please, it seems to convert the CSS `{String}` into an CJS export according to the given pattern and therefore breaks ETWP, probably won't fix

**Comment by evilebottnawi** [comment] 2017-08-18 09:59
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2017-08-18 09:59 UTC
