### ISSUE TITLE
Use options on loaders with extract-text-webpack-plugin

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [webpack-contrib/extract-text-webpack-plugin#468] opened 2017-03-28 13:38 UTC
For example, let say we have two rules, one to manage common scss/css files and another one to manage useable css/scss files.

In the first one we used extract-text-webpack-plugin to achieve cool enhancements to our css (as pointed [here](https://webpack.js.org/plugins/extract-text-webpack-plugin/)) (please see this rule below).

And, in the same vein, we would like to use this cool enhancements in the second kind of files too (useable scss/css), but at this time we need to add special options to the loader (in this case the sass-loader). In the docs we don't have a clear option how to do this.

So, first a question, can we do this on some way?
And if not, I would appreciate if this issue were added to the enhancement list.

**common css/scss files rule**
```
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  exclude: /\.useable\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: ['css-loader', 'postcss-loader', 'sass-loader']
  })
}

```

**useable scss/css files rule**

```
var path = require('path');
let node_modules_path = path.resolve(__dirname, '../../../', 'node_modules');

module.exports = {
  test: /\.useable\.(scss|sass|css)$/i,
  use: [
    {loader: "style-loader/useable"},
    {loader: "css-loader"},
    {
      loader: "sass-loader",
      options: {
        includePaths: [node_modules_path]
      }
    },
  ],
}
```

**Comment by eyolas** [comment] 2017-03-31 13:34
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/test/cases/simple-queryless-object/webpack.config.js

**Comment by Danilo-Araujo-Silva** [comment] 2017-04-01 12:09
This is interesting so I tried.

If I use this (without extract-text-webpack-plugin):

```
var path = require('path');
let assets_stylesheets = path.resolve(__dirname, '../../../', 'app', 'assets', 'stylesheets');
let node_modules_path = path.resolve(__dirname, '../../../', 'node_modules');

module.exports = {
  test: /\.(scss|sass|css)$/i,
  exclude: /\.useable\.(scss|sass|css)$/i,
  use: [
    {loader: "style-loader/useable"},
    {loader: "css-loader"},
    {
      loader: "sass-loader",
      options: {
        includePaths: [
          assets_stylesheets,
          node_modules_path
        ]
      }
    },
  ],
}
```

I can use `@import '~sanitize.css/sanitize.css' `.

But if I use extract-text-webpack-plugin like this:

```
var path = require('path');

const ExtractTextPlugin = require('extract-text-webpack-plugin');

let assets_stylesheets = path.resolve(__dirname, '../../../', 'app', 'assets', 'stylesheets');
let node_modules_path = path.resolve(__dirname, '../../../', 'node_modules');

module.exports = {
  test: /\.(scss|sass|css)$/i,
  exclude: /\.useable\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {loader: 'css-loader'},
      {loader: 'postcss-loader'},
      {
        loader: "sass-loader",
        options: {
          includePaths: [
            assets_stylesheets,
            node_modules_path
          ]
        }
      },
    ]
  })
};
```

not works. Why?

**Comment by nsfmc** [comment] 2017-04-05 23:30
fwiw, i'm running into this problem as well, in my case i assumed it was a problem with postcss-loader and debugged that whole chain until i realized that it only failed for the postcss loaders inside the extract-text-plugin, in my case, i noticed that the options it was passing to the plugin were just `{}` despite initializing it like

```javascript
ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      {
        loader: 'postcss-loader',
        options: {
          plugins: function() {
            return [require('autoprefixer'), require('postcss-flexbugs-fixes')];
          },
        },
      },
    ],
  })
```

anyhow, in my case, there is something of a gross workaround, but the ability to pass loader objects to this plugin seems off.

**Comment by jonathansousa** [comment] 2017-04-20 14:10
I'm running into this issue as well when trying to turn css minimization on for production files. I think I went through the same process of debugging every other possibility before realizing it was the inability of the extract-text-plugin to pass options to the css loader. So far I haven't found a work-around.

**Comment by michael-ciniawsky** [comment] 2017-04-22 09:25
If I not mistaken this  was a 'bug' in webpack =< 2.2.1 where `function || require()` in loader options where not correctly stringified if an `ident` is missing

```js
...
{
   loader: 'some-loader',
   options: {
      ident: 'some',
      option: option()
   }
}
```

Please try with either using `ident` or by upgrading to the latest webpack (>= 2.2.1). Reopen if still any regressions :)

**Comment by nsfmc** [comment] 2017-04-22 22:53
@michael-ciniawsky i was experiencing this with `webpack@2.3.3`

**Comment by michael-ciniawsky** [comment] 2017-04-23 07:49
@nsfmc Then please provide more info (`webpack.confg.js`, error logs, source) 😛

**Comment by Danilo-Araujo-Silva** [comment] 2017-04-23 18:31
My code and logs are above. That code was using webpack 2.3.2.
Reopen?

**Comment by nsfmc** [comment] 2017-04-23 20:51
thanks @michael-ciniawsky i'm working on a minimal testcase/repo for this right now, it may be that the error is in `postcss-load-config` but i will report back once i have isolated it more thoroughly, thanks for being patient with me.

**Comment by nsfmc** [comment] 2017-04-23 23:41
i just wanted to add some more color here to the discussion. after doing a lot more testing this afternoon, i found that _my_ problem was actually in `postcss-loader` and appears to be fixed by https://github.com/postcss/postcss-loader/pull/201 

@Danilo-Araujo-Silva i noticed that you also use postcss with `extract-text-plugin`, could you let me know if changing your `postcss-loader` package.json requirement to this fixes things?

```diff
-    "postcss-loader": "^1.3.3",
+    "postcss-loader": "nsfmc/postcss-loader#3691cb757845599d2a5d97171daeda7d9be3f7f5",
```

hope all's well and everyone's having a good weekend

**Comment by michael-ciniawsky** [comment] 2017-04-24 00:25
@nsfmc See comment in [postcss/postcss-loader#201](https://github.com/postcss/postcss-loader/pull/201)

**Comment by jonathansousa** [comment] 2017-04-24 15:29
After another round of debugging it looks like my situation is a case of a bug in css-loader not properly receiving options being passed correctly from extract-text-webpack-plugin. This bug was patched up in the 0.27.0 release -- extract-text-webpack-plugin devDependencies are at ^0.26.1 which was the version I had installed --
 so updating css-loader independently to the latest version cleared things up for me. Thanks for the idea to go back and take another look at the dependencies.

**Comment by Danilo-Araujo-Silva** [comment] 2017-04-27 20:13
@nsfmc, looks like using your code the problem is fixed (at least in the main case). If I use the line below

`let headCSS = require('!style-loader/useable!css-loader!postcss-loader!sass-loader!head.scss');
headCSS.use();`

with a call to `@import '~sanitize.css/sanitize.css';` inside of it, when using your package on package.json, the system compiles ok. When changing to the common postcss package I get a compiler error.

Unfortunately (and maybe this happens because I don't know exactly how to use the webpack-extract-plugin yet) when I try to use a `.useable.scss` the code not works.

The useable scss loader that I'm using is as follows:

```
var path = require('path');
let assets_stylesheets = path.resolve(__dirname, '../../../', 'app', 'assets', 'stylesheets');
let node_modules_path = path.resolve(__dirname, '../../../', 'node_modules');

const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  test: /\.useable\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader/useable',
    use: [
      {loader: "css-loader"},
      {loader: "postcss-loader"},
      {
        loader: "sass-loader",
        options: {
          includePaths: [
            assets_stylesheets,
            node_modules_path
          ]
        }
      },
    ]
  })
};

```
I'm receiving a empty object:

```
Object {}
```

and I'm getting the following error:

```
head.ts:41 Uncaught TypeError: testCSS.use is not a function
    at Object.defineProperty.value (head.ts:41)
    at __webpack_require__ (bootstrap 987f31d…:19)
    at Object.<anonymous> (head.js:1)
    at __webpack_require__ (bootstrap 987f31d…:19)
    at Object.<anonymous> (head.js:3)
    at __webpack_require__ (bootstrap 987f31d…:19)
    at Object.<anonymous> (head.js:12692)
    at __webpack_require__ (bootstrap 987f31d…:19)
    at Object.<anonymous> (string.ts:17)
    at __webpack_require__ (bootstrap 987f31d…:19)
Object.defineProperty.value @ head.ts:41
__webpack_require__ @ bootstrap 987f31d…:19
(anonymous) @ head.js:1
__webpack_require__ @ bootstrap 987f31d…:19
(anonymous) @ head.js:3
__webpack_require__ @ bootstrap 987f31d…:19
(anonymous) @ head.js:12692
__webpack_require__ @ bootstrap 987f31d…:19
(anonymous) @ string.ts:17
__webpack_require__ @ bootstrap 987f31d…:19
module.exports.ctor.super_ @ bootstrap 987f31d…:65
(anonymous) @ bootstrap 987f31d…:65
rails.js:555 Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (rails.js:555)
    at __webpack_require__ (bootstrap 987f31d…?86f2:19)
    at Object.defineProperty.value (body.ts:24)
    at __webpack_require__ (bootstrap 987f31d…?86f2:19)
    at lazyLoader (body.js:5)
    at Object.<anonymous> (body.js:8)
    at __webpack_require__ (bootstrap 987f31d…?86f2:19)
    at Object.<anonymous> (body.js:2)
    at __webpack_require__ (bootstrap 987f31d…?86f2:19)
    at Object.<anonymous> (emitter.js?824b:2)
(anonymous) @ rails.js:555
__webpack_require__ @ bootstrap 987f31d…?86f2:19
Object.defineProperty.value @ body.ts:24
__webpack_require__ @ bootstrap 987f31d…?86f2:19
lazyLoader @ body.js:5
(anonymous) @ body.js:8
__webpack_require__ @ bootstrap 987f31d…?86f2:19
(anonymous) @ body.js:2
__webpack_require__ @ bootstrap 987f31d…?86f2:19
(anonymous) @ emitter.js?824b:2
__webpack_require__ @ bootstrap 987f31d…?86f2:19
(anonymous) @ body.js:21299
__webpack_require__ @ bootstrap 987f31d…?86f2:19
module.exports.ctor.super_ @ bootstrap 987f31d…?86f2:65
(anonymous) @ bootstrap 987f31d…?86f2:65
```

Looks like we are almost.

For now, using without a `useable.scss` is a valid workaround. And I'm not sure if this is a issue on webpack-extract-plugin or in postcss.

**Comment by nsfmc** [comment] 2017-04-28 17:18
@Danilo-Araujo-Silva if you look at that pr i mention in the later comment, it looks like my fix certainly addresses *something* but further testing seems to show that my issue at least is in postcss-loader's handling of the config option defaulting to the postcss.config.js although i remain confused about why it finds the configuration the first time but not subsequent times.

**Comment by alexander-akait** [comment] 2019-05-29 12:02
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin

**Closed by alexander-akait** 2019-05-29 12:02 UTC
Labels: type: Bug
