### ISSUE TITLE
Cannot find module 'webpack/lib/ConcatSource'

### ISSUE THREAD

**Issue by b82** [webpack-contrib/extract-text-webpack-plugin#133] opened 2015-11-30 13:43 UTC
I get immediately this error after only declare the plugin.
This is my config.webpack.js

``` javascript
var ExtractTextPlugin = require("extract-text-webpack-plugin");
module.exports = {
    entry: './main.jsx',
    output: {
        filename: './public/js/build/bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel',
                query: {
                  presets: ['react', 'es2015']
                }
            },
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            },
            {
                test: /\.(jpg|png|otf|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'url-loader?limit=100000'
            }
        ]
    }
}
```

Can't understand why

**Comment by neglectedvalue** [comment] 2015-12-21 22:05
Hi, @b82! The same trouble. Have you resolved it?

**Comment by b82** [comment] 2015-12-22 10:07
@neglectedvalue , try this micro-confguration, I didn't had any error with this:

**webpack.config.js**
```
var ExtractTextPlugin = require('extract-text-webpack-plugin');
module.exports = {
	entry: './app.jsx',
	output: {
		filename: 'bundle.js'
	},
	module: {
		loaders: [
			{
				test: /\.jsx?$/,
				exclude: /(node_modules|bower_components)/,
	                        loader: 'babel',
	                        query: {
                                    presets: ['react', 'es2015']
                               }
        	        }
		]
	}
}
```

**package.json**
```
"devDependencies": {
    "babel-core": "^6.3.21",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "extract-text-webpack-plugin": "^0.9.1",
    "webpack": "^1.12.9"
  },
  "dependencies": {
    "react": "^0.14.3",
    "react-dom": "^0.14.3"
  }
```

Start with this and do some experiments, let me know!

**Comment by jasonslyvia** [comment] 2016-02-19 02:45
Are you guys using webpack@2.x ? It seems like there is no `webpack/lib/ConcatSource` in webpack@2.x package.

**Comment by nspaeth** [comment] 2016-02-23 18:20
Try using the `extract-text-webpack-plugin-webpack-2` package.

**Comment by bebraw** [comment] 2017-01-28 08:53
I think this should be fixed in version 2. Feel free to re-open if you can still reproduce this.

**Closed by bebraw** 2017-01-28 08:53 UTC

**Comment by Airomad** [comment] 2017-05-22 11:10
the same error

**Comment by bebraw** [comment] 2017-05-22 11:10
@Airomad Can you open a separate issue with more information?

**Comment by HosseinAgha** [comment] 2017-06-14 10:55
have it fixed yet?

**Comment by bebraw** [comment] 2017-06-14 11:01
@HosseinAgha I don't know. If you are getting the error, please open a separate issue with enough information to debug.

**Comment by HosseinAgha** [comment] 2017-06-14 11:23
@bebraw sorry that was my mistake I was using an older version

**Comment by jeblister** [comment] 2017-07-11 16:22
For me this error 
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
```
I'm on Linux and using the last nodejs v8.1.3

**Comment by evilebottnawi** [comment] 2017-07-11 16:31
@jeblister `npm i extract-text-webpack-plugin` ?

**Comment by jeblister** [comment] 2017-07-11 17:07
@evilebottnawi i fix it but using `npm i -g extract-text-webpack-plugin` because the [preact-cli ](https://github.com/developit/preact-cli) need it.

**Comment by evilebottnawi** [comment] 2017-07-11 17:18
@jeblister if your use `npm@5` maybe bug in npm (there are many bugs in npm@5)

**Comment by shadowray** [comment] 2017-08-24 15:26
This issue may occur due to webpack components unavailability. 
In case you've installed webpack globally, try to link it up with your root directory.
`npm link webpack --save`
Or uninstall globally:
 `npm uninstall -g webpack` 
and then install it locally, like that:
`npm install --save html-webpack-plugin webpack webpack-dev-server`

Hope this helps.
