### ISSUE TITLE
Unable to HMR (Hot Module Replacement) css with version 3.0.0

### ISSUE THREAD

**Issue by Plortinus** [webpack-contrib/extract-text-webpack-plugin#592] opened 2017-08-05 01:31 UTC
**Versions:**
webpack 3.4.1
webpack-dev-server: 2.6.1
extract-text-webpack-plugin: 3.0.0

There is a pull request about [Hot module replacement](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/89). It was accepted in [version 2.2.0](https://github.com/webpack-contrib/extract-text-webpack-plugin/milestone/2). But there is no v2.2.0.
Now I updated the package to the version 3.0.0,but the HMR not works.

**Comment by cletusw** [comment] 2017-08-11 18:01
It wasn't ever merged. It was Closed with *unmerged changes* for 2.2.0, not accepted: https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/89#issuecomment-284304963

**Comment by evilebottnawi** [comment] 2017-08-18 11:12
@Plortinus @cletusw because PR was abandoned, feel free to recreate PR, thanks!

**Comment by evilebottnawi** [comment] 2017-09-13 13:21
@Plortinus @cletusw also can you create minimum reproducible test repo? It is allow to find solutoin more faster, thanks!

**Comment by Plortinus** [comment] 2017-09-13 15:07
@evilebottnawi [issue592 repro](https://github.com/Plortinus/issue592)

**Comment by d3viant0ne** [comment] 2017-10-16 13:28
As stated in the referenced pull request....

![screen shot 2017-10-16 at 8 22 54 am](https://user-images.githubusercontent.com/8420490/31614230-41c36b6c-b24b-11e7-9d1c-59f8ec5910ac.png)

It is not a but, it's not supported in etwp & is not going to be. I use HMR every day via style-loader, this is the recommended path unless you want to give @faceyspacey's plugin a go. He actively develops / supports it  & it should cover your use case.

**Closed** 2017-10-16 13:29 UTC
Labels: flag: Community help wanted, priority: 5 (nice to have), semver: Patch, severity: 3 (broken), type: Bug
