### ISSUE TITLE
[3.0.0-beta.3] CSS files exported in random order

### ISSUE THREAD

**Issue by botond-veress** [webpack-contrib/extract-text-webpack-plugin#558] opened 2017-06-29 16:09 UTC
I've upgraded to webpack@3.0.0 and extract-text-webpack-plugin@3.0.0-beta.3 but I am experimenting some issues. The order of my css files aren't kept anymore. It doesn't matter if I import it from javascript or from another sass file, they get mixed up even between builds made with the webpack-dev-server.

Example: I have 3 modules and they should be loaded in this order: A, A1 and A2. After I start the webpack-dev-server (with --watch) I get the ouput: A1, A, A2 then I modify one of the stylesheets to trigger the build again and the output becomes A, A2, A1 (it seems kind of random).

Any ideas what I am doing wrong? Or is this intended?

Note: It was working flawlessly with webpack@2.6.1 and extract-text-webpack-plugin@2.1.2 (and it still works).
Note 2: The order is important because I am importing some external fonts and they just doesn't work if they are injected in the middle of the css.

**Comment by d3viant0ne** [comment] 2017-06-29 20:14
@botond-veress - This is a duplicate of #548 

The issue is known, has been repro'd and the fix is in progress. See the linked issue for more information.

**Closed by d3viant0ne** 2017-06-29 20:14 UTC
Labels: priority: 2 (urgent), severity: 3 (broken), status: Needs repro, type: Bug
