### ISSUE TITLE
Sass-loader, Webpack 3 and Extract Text not working

### ISSUE THREAD

**Issue by cemlacrosse** [webpack-contrib/extract-text-webpack-plugin#600] opened 2017-08-14 13:55 UTC
Here is my web.config.js. It's not generating the 'commons.css' in the output folder.

/*eslint-disable */
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CleanPlugin = require('clean-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { AureliaPlugin } = require('aurelia-webpack-plugin');

const path = require('path');

var config = require('./project.build.config.js');

var filesToCopy = [];

//create list of index.html files to be copied to wwwroot
config.apps.forEach(app => {
  filesToCopy.push({ from: app.src + '.html', to: config.outDir + app.dest });
});

config.assets.forEach(asset => {
  filesToCopy.push(asset);
});

var plugins = [

  new CleanPlugin(config.outDir),

  new AureliaPlugin({ aureliaApp: undefined }),

  new webpack.optimize.CommonsChunkPlugin({ name: 'commons', filename: 'commons.js' }),

  new ExtractTextPlugin({
    filename: 'commons.css',
    disable: false,
    allChunks: true
  }),

  new CopyWebpackPlugin(filesToCopy, { copyUnmodified: false }),
  new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery",
  }),
];

var webpackBaseConfig = {

  entry: {
    app: [
      'materialize-loader!./materialize.config.js',
      'babel-polyfill',
      'aurelia-bootstrapper'
    ]
  },

  output: {
    path: config.outDir,
    chunkFilename: '[name]-[chunkhash].js',
    filename: '[name].js'
  },

  plugins: plugins,

  resolve: {
    extensions: ['.js'],
    alias: {
      '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
      'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
    }
  },

  module: {
    rules: [{
        test: /\.js?$/,
        include: /src/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          //resolve-url-loader may be chained before sass-loader if necessary
          use: ['css-loader', 'sass-loader']
        })
      },
      {
        test: /\.html?$/,
        include: /src/,
        exclude: /node_modules/,
        loader: 'html-loader'
      },
      {
        test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url-loader?limit=10000&mimetype=application/font-woff"
      }, {
        test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url-loader?limit=10000&mimetype=application/font-woff"
      }, {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url-loader?limit=10000&mimetype=application/octet-stream"
      }, {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        loader: "file-loader"
      }, {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url-loader?limit=10000&mimetype=image/svg+xml"
      }, {
        test: /\.(png|gif|jpe|ico)$/i,
        loader: 'file-loader?limit=10000'
      }
    ]
  },
};

module.exports = webpackBaseConfig;
/*eslint-enable */

**Comment by evilebottnawi** [comment] 2017-08-14 14:03
@cemlacrosse please provide minimum reproducible test repo, it is hard to read code in issue and difference to reproduce without repo, thanks!

**Comment by cemlacrosse** [comment] 2017-08-14 14:49
@evilebottnawi I created this repo that uses the same versions of webpack, extract and sass-loader. 

https://github.com/cemlacrosse/super-minimal-aurelia

steps: 
git clone repo 
npm install
run webpack

**Comment by evilebottnawi** [comment] 2017-08-14 15:03
@cemlacrosse thanks!

**Comment by cemlacrosse** [comment] 2017-08-14 16:11
@evilebottnawi I got the sample repo project working with sass. Still haven't gotten it working with my real project which is not possible to put in a github repo.

**Comment by evilebottnawi** [comment] 2017-08-15 17:19
@cemlacrosse why your expect `commons.css`? Your don't have configuration for this. If your want to generate `common.css` your can use this example (https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points-commons-chunk-css-bundle). 

Based on first post in issue try to remove `allChunks: true`, use `filename: '[name].css',` instead `filename: 'commons.css'. `CommonsChunkPlugin` plugin create `common.js` and your `chunk` when we should extract all css from `common.js` and your `chunk` using `ExtractTextPlugin`. Also your can use `minChunks` as function to filter modules which your want to have in `common.js`, example (get files only from `node_modules`):
```shell
 minChunks: module =>
        module.resource &&
        /\.js$/.test(module.resource) &&
        module.resource.indexOf(appNodeModules) !== -1,
```
Thanks!

**Comment by cemlacrosse** [comment] 2017-08-15 18:05
@evilebottnawi I'm trying to upgrade an aurelia webpack 1.x project to the current versions of all the libraries. I'm finding this to be extremely difficult. This is what the original webpack.base.config looks like.

```
/*eslint-disable */
var webpack = require('webpack');
var ExtractCss = require('extract-text-webpack-plugin');
var CleanPlugin = require('clean-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var AureliaWebpackPlugin = require('aurelia-webpack-plugin');
var path = require('path');

var config = require('./project.build.config.js');

var filesToCopy = [];

//create list of index.html files to be copied to wwwroot
config.apps.forEach( app =>
{
	filesToCopy.push({ from: app.src + '.html', to: config.outDir + app.dest });
});

config.assets.forEach( asset =>
{
	filesToCopy.push(asset);
});


var plugins = [

	new CleanPlugin(config.outDir),

	new AureliaWebpackPlugin(),

	new webpack.optimize.CommonsChunkPlugin({
		name: "commons",
		// (the commons chunk name)

		filename: "commons.js",
		// (the filename of the commons chunk)

		minChunks: 3,
		// (Modules must be shared between 3 entries)

		// chunks: ["pageA", "pageB"],
		// (Only use these entries)
	}),

	new webpack.optimize.CommonsChunkPlugin("commons", "commons.js"),

	new ExtractCss('commons.css', {disable:false, allChunks:false}),

	new CopyWebpackPlugin(filesToCopy, {copyUnmodified:false}),

	new webpack.ProvidePlugin({
		$: "jquery",
		jQuery: "jquery",
		"window.jQuery": "jquery",
	}),
];

// create the apps entry points
var entryPoints = {};
config.apps.forEach( app =>
{
	entryPoints[app.name] = [ 'materialize-loader!./materialize.config.js', 'babel-polyfill', 'whatwg-fetch', app.src];
});

var webpackBaseConfig =
{

	entry:entryPoints,

	output:
	{
		path: config.outDir,
		chunkFilename: '[name]-[chunkhash].js',
		filename: '[name].js'
	},

	plugins:plugins,

	resolve: {
		extensions: ['', '.js'],
		alias: {
			'$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
			'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
		}
	},

	module: {
		loaders: [
			{
				test: /\.js?$/,
				include: /src/,
				loader: 'babel', // 'babel-loader' is also a legal name to reference
				query: {
					cacheDirectory: true,
					presets: ['es2015-loose', 'stage-1'],
					plugins: ['transform-decorators-legacy']
				}
			},
			{
				test: /\.css$/,
				loader: ExtractCss.extract('style-loader', 'css-loader')
			},
			{
				test: /\.scss?$/,
				loader: ExtractCss.extract('style', 'css-loader!sass-loader')
			},
			{
				test: /\.html?$/,
				loader: 'html'
			},
			{
				test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
				loader: "url?limit=10000&mimetype=application/font-woff"
			}, {
				test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
				loader: "url?limit=10000&mimetype=application/font-woff"
			}, {
				test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
				loader: "url-loader?limit=10000&mimetype=application/octet-stream"
			}, {
				test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
				loader: "file-loader"
			}, {
				test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
				loader: "url-loader?limit=10000&mimetype=image/svg+xml"
			}, {
                test: /\.(png|gif|jpe|ico)$/i,
                loader: 'file?limit=10000'
            }
		],
		preLoaders: [
			{
				test: /\.js/,
				loader: 'eslint',
				include: /src/,
				exclude:/(node_modules|thirdparty|errors)/
			}
		]
	},
};

module.exports = webpackBaseConfig;
/*eslint-enable */


```

**Comment by evilebottnawi** [comment] 2017-08-15 18:10
@cemlacrosse for `ExtractCss` use:
```shell
ExtractCss({
  disable: false,
  filename: "[name].css",
  allChunks: true
})
```

**Comment by cemlacrosse** [comment] 2017-08-15 19:02
@evilebottnawi I tried that. It's still not writing the commons.css file in the output directory.
```
/*eslint-disable */
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CleanPlugin = require('clean-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var AureliaWebpackPlugin = require('aurelia-webpack-plugin');
var path = require('path');

var config = require('./project.build.config.js');

var filesToCopy = [];

//create list of index.html files to be copied to wwwroot
config.apps.forEach(app => {
  filesToCopy.push({ from: app.src + '.html', to: config.outDir + app.dest });
});

config.assets.forEach(asset => {
  filesToCopy.push(asset);
});


var plugins = [

  new CleanPlugin(config.outDir),

  new AureliaWebpackPlugin.AureliaPlugin({ aureliaApp: undefined }),

  new webpack.optimize.CommonsChunkPlugin({
    name: "commons",
    // (the commons chunk name)

    filename: "commons.js",
    // (the filename of the commons chunk)

    minChunks: 3,
    // (Modules must be shared between 3 entries)

    // chunks: ["pageA", "pageB"],
    // (Only use these entries)
  }),

  new webpack.optimize.CommonsChunkPlugin({
    name: 'commons',
    filename: 'commons.js'
  }),

  new ExtractTextPlugin({
    disable: false,
    filename: "[name].css",
    allChunks: true
  }),

  new CopyWebpackPlugin(filesToCopy, { copyUnmodified: false }),

  new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery",
  }),
];

// create the apps entry points
var entryPoints = {};
config.apps.forEach(app => {
  entryPoints[app.name] = ['materialize-loader!./materialize.config.js', 'babel-polyfill', 'whatwg-fetch', 'aurelia-bootstrapper'];
});

var webpackBaseConfig = {

  entry: entryPoints,

  output: {
    path: config.outDir,
    chunkFilename: '[name]-[chunkhash].js',
    filename: '[name].js'
  },

  plugins: plugins,

  resolve: {
    extensions: ['.js'],
    modules: ['src', 'node_modules'],
    alias: {
      '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
      'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
    }
  },

  module: {
    rules: [{
        test: /\.js$/i,
        loaders: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: [
            ['env', { loose: true, modules: true }]
          ],
          plugins: ['transform-class-properties', 'transform-decorators-legacy']
        }
      },
      {
        test: /\.css$/i,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader'
        }),
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          use: ['css-loader', 'sass-loader']
        })
      },
      {
        test: /\.html?$/i,
        use: 'html-loader'
      },
      {
        test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
        use: "url-loader?limit=10000&mimetype=application/font-woff"
      },
      {
        test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
        use: "url-loader?limit=10000&mimetype=application/font-woff"
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        use: "url-loader?limit=10000&mimetype=application/font-woff"
      },
      {
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        use: "file-loader"
      },
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        use: "url-loader?limit=10000&mimetype=image/svg+xml"
      },
      {
        test: /\.(png|gif|jpe|ico)$/i,
        use: 'file-loader?limit=10000'
      }
    ]
  },
};

module.exports = webpackBaseConfig;
/*eslint-enable */

```

**Comment by evilebottnawi** [comment] 2017-08-16 10:18
@cemlacrosse it is not works? If yes which error your get?

**Comment by cemlacrosse** [comment] 2017-08-16 12:57
@evilebottnawi it's still not working. There are just fewer output files with no error messages after the updates.   It's not writing *.css, *.woff2 and *.eot files to the output folder like it did before the updates.

This is the old output before the updates.
```

"Start bundling"
Executing additional scripts before exit
Hash: edcd38b9b3f27c4df69e
Version: webpack 1.13.2
Time: 10770ms
                                 Asset       Size  Chunks             Chunk Names
39b2c3031be6b4ea96e2e3e95d307814.woff2      50 kB          [emitted]  
  dfe56a876d0282555d1e2458e278060f.eot    21.7 kB          [emitted]  
 7500519de3d82e33d1587f8042e2afcb.woff    61.6 kB          [emitted]  
  94998475f6aea65f558494802416c1cf.ttf     128 kB          [emitted]  
  a990f611f2305dc12965f186c2ef2690.eot    20.9 kB          [emitted]  
69f8a0617ac472f78e45841323a3df9e.woff2    49.4 kB          [emitted]  
 3b813c2ae0d04909a33a18d792912ee7.woff    62.3 kB          [emitted]  
  46e48ce0628835f68a7369d0254e4283.ttf     127 kB          [emitted]  
  30799efa5bf74129468ad4e257551dc3.eot    21.3 kB          [emitted]  
2751ee43015f9884c3642f103b7f70c9.woff2    49.2 kB          [emitted]  
 ba3dcd8903e3d0af5de7792777f8ae0d.woff    61.7 kB          [emitted]  
  df7b648ce5356ea1ebce435b3459fd60.ttf     126 kB          [emitted]  
  4d9f3f9e5195e7b074bb63ba4ce42208.eot    21.4 kB          [emitted]  
574fd0b50367f886d359e8264938fc37.woff2    50.2 kB          [emitted]  
 fc78759e93a6cac50458610e3d9d63a0.woff      63 kB          [emitted]  
  894a2ede85a483bf9bedefd4db45cdb9.ttf     127 kB          [emitted]  
  ecdd509cadbf1ea78b8d2e31ec52328c.eot      21 kB          [emitted]  
954bbdeb86483e4ffea00c4591530ece.woff2    48.5 kB          [emitted]  
 dc81817def276b4f21395f7ea5e88dcd.woff    62.9 kB          [emitted]  
  e31fcf1885e371e19f5786c2bdfeae1b.ttf     128 kB          [emitted]  
  04e13158c8cf15ff8687e1af8b1105f7.png       5 kB          [emitted]  
  a2ce4f1850f542ff4ee46aac30658ffa.ico    1.15 kB          [emitted]  
                               /app.js    1.08 MB    0, 2  [emitted]  /app
           app-2df9b6410277861dcec0.js    2.04 MB    1, 2  [emitted]  app
                            commons.js    3.76 kB       2  [emitted]  commons
                           commons.css     158 kB    0, 2  [emitted]  /app
                           /app.js.map    1.37 MB    0, 2  [emitted]  /app
                       commons.css.map   88 bytes    0, 2  [emitted]  /app
       app-2df9b6410277861dcec0.js.map    2.34 MB    1, 2  [emitted]  app
                        commons.js.map    3.83 kB       2  [emitted]  commons
                            index.html    1.06 kB          [emitted]  
                activate/Activate.html    1.22 kB          [emitted]  
            activate/Unauthorized.html  309 bytes          [emitted]  
      images/user_icon_placeholder.png       5 kB          [emitted]  
                           favicon.ico    1.15 kB          [emitted]  
   [0] multi /app 64 bytes {0} [built]
 [378] ./src ^\.\/.*$ 24.7 kB {1} [built]
    + 959 hidden modules
Child extract-text-webpack-plugin:
        + 23 hidden modules
```
This is the new output with the missing files after the updates.
```
"Start bundling"
Executing additional scripts before exit
Hash: d439fd05ca0b30ea3a19
Version: webpack 3.4.1
Time: 3078ms
                                 Asset       Size  Chunks                    Chunk Names
 eed9aab5449cc9c8430d7d258108f602.woff    90.3 kB          [emitted]
1f35e6a11d27d2e10d28946d42332dc5.woff2    63.1 kB          [emitted]
3c37aa69cd77e6a53a067170fa8fe2e9.woff2    64.3 kB          [emitted]
 ea36cd9a0e9eee97012a67b8a4570d7b.woff    89.7 kB          [emitted]
5136cbe62a63604402f2fedb97f246f8.woff2    64.8 kB          [emitted]
 3cf6adf61054c328b1b0ddcd8f9ce24d.woff    89.8 kB          [emitted]
1561b424aaef2f704bbd89155b3ce514.woff2    65.4 kB          [emitted]
 cf4d60bc0b1d4b2314085919a00e1724.woff    90.6 kB          [emitted]
c0f1e4a4fdfb8048c72e86aadb2a247d.woff2    64.8 kB          [emitted]
 44b78f142603eb69f593ed4002ed7a4a.woff    88.1 kB          [emitted]
                               /app.js    1.21 MB       0  [emitted]  [big]  /app
                            commons.js    5.88 kB       1  [emitted]         commons
                           /app.js.map    1.45 MB       0  [emitted]         /app
                        commons.js.map       6 kB       1  [emitted]         commons
                            index.html    1.06 kB          [emitted]
            activate/Unauthorized.html  309 bytes          [emitted]
                activate/Activate.html    1.22 kB          [emitted]
      images/user_icon_placeholder.png       5 kB          [emitted]
                           favicon.ico    1.15 kB          [emitted]
  [59] (webpack)/buildin/global.js 509 bytes {0} [built]
 [148] multi aurelia-webpack-plugin/runtime/pal-loader-entry materialize-loader!./materialize.config.js babel-polyfill whatwg-fetch aurelia-bootstrapper 76 bytes {0} [built]
 [151] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
 [152] ./node_modules/materialize-loader/index.loader.js!./materialize.config.js 312 bytes {0} [built]
 [153] ./node_modules/style-loader!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/materialize-loader/materialize-styles.loader.js!./materialize.config.js 1.34 kB {0} [built]
 [154] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/materialize-loader/materialize-styles.loader.js!./materialize.config.js 215 kB {0} [built]
    + 403 hidden modules

```

**Comment by evilebottnawi** [comment] 2017-08-16 13:03
@cemlacrosse just update your test repo with new config, but it is not bug it is just question about how configure your configuration, more suitable place for this is `stackoverflow`, we have a lot of issue every day.

**Comment by cemlacrosse** [comment] 2017-08-16 15:26
@evilebottnawi Thanks. I think that I maybe solved my ExtractTextPlugin problem.

**Comment by althamash-chaipoint** [comment] 2017-08-17 06:54
@cemlacrosse I am facing a similar issue. How were you able to fix this?

**Comment by evilebottnawi** [comment] 2017-08-17 09:06
@althamash-chaipoint seems it is just invalid configuration, without test repo it is difficult says something about problem

**Comment by cemlacrosse** [comment] 2017-08-17 13:20
@althamash-chaipoint It was the configuration. They seem to be changing how you have to configure it. It's a moving target. What works now may not work in the next release. And Aurelia is still working with my current configuration. I'm stilling working out the bugs with the aurelia-webpack-plugin. 

This is part of the configuration for the Extract Text Plugin. Your entry point also matters a lot because that tells webpack what files it needs to include in the build.

```
// imports
var ExtractTextPlugin = require('extract-text-webpack-plugin');

//plugins
new ExtractTextPlugin({
    disable: false,
    filename: 'commons.css',
    allChunks: true
  }),

//module rules
       test: /\.css$/i,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader'
        }),
      },
      {
        test: /\.scss$/i,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          use: ['css-loader', 'sass-loader']
        })
```

**Comment by IvanKalinin** [comment] 2017-08-17 18:47
I have the same issue using 
`"extract-text-webpack-plugin": "^3.0.0",`
`"webpack": "^3.5.5",`

[webpack.config.js](https://gist.github.com/IvanKalinin/789abe68feb6bfde066574463d43deef)

There is no any errors/warnings in console. The styles just don't loads in the document.

**Comment by althamash-chaipoint** [comment] 2017-08-18 02:22
If it helps anyone, I made a mistake when importing the scss file. I changed the import statement from
`import ('./test.scss')`
to
`import './test.scss'`
Refer [https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/607](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/607)

**Comment by evilebottnawi** [comment] 2017-08-18 09:06
@IvanKalinin @althamash-chaipoint please create new issue, don't write own problems in this issue, because it is likely not to be answered, thanks!
@cemlacrosse can we close this issue?

**Comment by nishanthnareddy** [comment] 2017-09-22 18:33
I was trying to create a separate bundle for css based on the chunks name using extract-text-webpack-plugin with webpack@3.6.0.

having the same issue.

I have added a web pack config in bitbucket server. please find it from below URL https://bitbucket.org/nishanth7475/webpackconfigalone/src/dca35d8c0eb31debfcefa2f7f282f987604b6d97?at=master

**Comment by evilebottnawi** [comment] 2018-02-01 14:02
Please don't write about your problem here. Create new issue with description and test repo. Thanks! Original issue was resolved.

**Closed by evilebottnawi** 2018-02-01 14:02 UTC
Labels: flag: Needs more info
