### ISSUE TITLE
Unexpected: "ERROR in <blah> doesn't export content"

### ISSUE THREAD

**Issue by roblg** [webpack-contrib/extract-text-webpack-plugin#42] opened 2014-11-15 06:43 UTC
When running `./node_modules/webpack/bin/webpack.js --watch`, an error shows up in the terminal after changing a CSS file ("ERROR in <blah> doesn't export content"), and the webpack compilation seems to run twice.

The high-level setup is as follows: two entry points, one (`OneEntry.js`) does a synchronous require of `Dep.js`, and the other (`TwoEntry.js`) does a require.ensure of `Dep.js`. `Dep.js` requires `Dep.css`. Changing `Dep.css` while running with `--watch` triggers the error message.

The final output doesn't seem to be affected (at least in my simple example here), but it's still a scary message. I started to step through it with node-debug, but didn't get much farther than figuring out where the error was coming from -- line 156 of `extract-text-webpack-plugin/index.js`. I'll probably look at it at little further tomorrow. 

**My webpack.config.js:**

``` javascript
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    target: "web",
    debug: true,
    // devtool: "source-map",
    entry: {
        One: './OneEntry.js',
        Two: './TwoEntry.js'
    },
    output: {
        path: "./target",
        filename: "[name].bundle.js"
    },
    module: {
        loaders: [            
            { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") },
        ]
    },
    plugins: [
        new ExtractTextPlugin("[name].styles.css")
    ]
};
```

**OneEntry.js**

``` javascript
require('./Dep.js');

module.exports = function () {
    console.log("OneEntry");
}
```

**TwoEntry.js**

``` javascript
module.exports = function () {
    require.ensure([], function (require) {
        var One = require('./Dep.js');
    });
}
```

**Dep.js**

``` javascript
require('./Dep.css');

module.exports = function helloWorld() {
    console.log("Hello, World!");
}
```

**Dep.css**

``` css
body {
    font-weight: normal;
}
```

Console output:

```
[10:30:58] extract-text-plugin-bug-repro$ ./node_modules/webpack/bin/webpack.js --watch
Hash: 1af67a17d8cdba702d4f
Version: webpack 1.4.13
Time: 123ms
         Asset  Size  Chunks             Chunk Names
 Two.bundle.js  3850       0  [emitted]  Two
 1.1.bundle.js   332       1  [emitted]
 One.bundle.js  1886    2, 1  [emitted]  One
One.styles.css    32    2, 1  [emitted]  One
   [0] ./OneEntry.js 81 {2} [built]
   [0] ./TwoEntry.js 113 {0} [built]
   [1] ./Dep.js 103 {1} {2} [built]
    + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Hash: 33291634f4065e501d4e
Version: webpack 1.4.13
Time: 24ms
         Asset  Size  Chunks             Chunk Names
 1.1.bundle.js   332       1  [emitted]
 One.bundle.js  1886    2, 1  [emitted]  One
One.styles.css    30    2, 1  [emitted]  One
    + 7 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Hash: 2ed4f9458139cfb59089
Version: webpack 1.4.13
Time: 8ms
         Asset  Size  Chunks             Chunk Names
 1.1.bundle.js  1253       1  [emitted]
 One.bundle.js  2807    2, 1  [emitted]  One
One.styles.css    30    2, 1  [emitted]  One
    + 7 hidden modules

ERROR in /path/extract-text-plugin-bug-repro/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/path/extract-text-plugin-bug-repro/node_modules/style-loader/index.js!/path/extract-text-plugin-bug-repro/node_modules/css-loader/index.js!/path/extract-text-plugin-bug-repro/Dep.css doesn't export content
```

**Comment by roblg** [comment] 2015-01-20 19:04
Updating title to reflect that we actually see this error in non-watch mode as well. We have a little hack that seems to fix the issue, but I'm not 100% sure it's the "right" fix.

**Comment by roblg** [comment] 2015-01-20 20:48
The original issue posted here said that the output wasn't affected, but it actually *does* seem to be affected some percentage of the time, which I think increases the severity of the bug.

After some debugging, I made a simple change that seems to fix the issue for us (the error messages go away, and it's been weeks since we had any corrupted output). I'm not entirely sure that the fix is correct -- there might be a better way to accomplish what I did, but I'm hoping someone more familiar with the code than me will take a quick look and be able to tell one way or the other.

Any help/guidance on this would be much appreciated. 

Commit: https://github.com/roblg/extract-text-webpack-plugin/commit/413f55bd8c953dd0b4109b501d026add5e11a6d8

**Comment by sokra** [comment] 2015-01-20 20:53
hmm ok I get the issue... If a module is in multiple chunks it is built multiple times in parallel (propably with different intents (one want to extract it, the other not)...

**Comment by nighca** [comment] 2015-04-30 02:44
Got this issue, too.
It's not rare that one module being used in multiple places(pages). If it is sync-required (style supposed to be extracted out) in one page while async-required (supposed not to be extracted) in another page, error shows up. Actually error only shows up while watching. If built directly (not watching), no error shows up while the module's style will not be packaged in the async-required chunk.

Hope to know if this will be fixed soon. Thx!

**Comment by nighca** [comment] 2015-04-30 02:48
Seems this is the same problem.

**Comment by aickin** [comment] 2015-07-17 05:04
I had difficulty applying @roblg's patch to the current codebase. With some tinkering, I was able to kind of sort of get it to work, but it broke hot reload.

Looking a little further into it, it seems like the problem is that the loader declares that its results are cacheable, and then the plugin mutates the results from the loader. When I commented out the two lines in loader that look like this:

```
if (this.cacheable) this.cacheable();
```

everything seemed to work fine, including hot reload. I'm not sure if that will cause any other problems, but it seems relatively safe to me. I'll make a PR.

**Comment by rosenfeld** [comment] 2016-02-22 17:45
Any updates or work-around for this bug? I had to disable the extract-text plugin for the time being in development (watch) mode and add some conditionals to the application, but I'm afraid bad things might happen in production only since I use a different set-up for the development mode :(

**Comment by roblg** [comment] 2016-02-22 18:01
@rosenfeld we ended up following @aickin's advice and making the plugin output non-cacheable.

He had a clever workaround to extend ExtractTextPlugin to fix the behavior -- no funky build-time step needed:

```
var ExtractTextLoader = require("extract-text-webpack-plugin/loader");

// we're going to patch the extract text loader at runtime, forcing it to stop caching
// the caching causes bug #49, which leads to "contains no content" bugs. This is
// risky with new version of ExtractTextPlugin, as it has to know a lot about the implementation.

module.exports = function(source) {
	this.cacheable = false;
	return ExtractTextLoader.call(this, source);
}

module.exports.pitch = function(request) {
	this.cacheable = false;
	return ExtractTextLoader.pitch.call(this, request);
}
```

(borrowed from: https://github.com/aickin/react-server/blob/master/packages/react-server-cli/src/NonCachingExtractTextLoader.js; no idea if that link will work forever)

**Comment by rosenfeld** [comment] 2016-02-22 18:13
I tried commenting the cacheable line before commenting in this thread and could confirm it worked, but on the other side it got much slower to update the output when the source changes, so I'm not sure whether it's better to disable caching for that plugin or to disable the plugin in watch mode... :(

**Comment by rosenfeld** [comment] 2016-02-22 19:06
@roblg, I'm curious. How do you combine this loader with other loaders? The documentation talks about using the extract method and inform the other loaders (style, css and sass in my case). I don't know how to combine this loader class with other loaders...

**Comment by rosenfeld** [comment] 2016-02-22 21:00
Nevermind, got it to work already.

**Comment by thebigredgeek** [comment] 2016-03-29 06:37
https://github.com/webpack/extract-text-webpack-plugin/pull/169

**Comment by mnpenner** [comment] 2016-06-21 16:03
I'm experiencing this issue with `--watch` periodically now too.

**Comment by andreechristian** [comment] 2016-09-06 06:46
+1, require.ensure problem?

**Comment by missyjcat** [comment] 2016-09-21 18:17
Here's a proposed fix following @aickin's suggestion that allows an `isCacheable` flag to be passed into the options. It worked for our implementation but we'd prefer not to fork and patch the plugin: #251

**Comment by nktssh** [comment] 2016-12-22 15:39
Have same issue after upgrading webpack (from `v2.2.0-rc.1` to `v2.2.0-rc.2`).
Can it be related to https://github.com/webpack/webpack/issues/3498 ?

**Comment by dalimian** [comment] 2017-01-07 03:09
I was having same issue (latest webpack and extract-text-plugin), the workaround to disable cache did not work for me. Making this change in .../node_modules/extract-text-webpack-plugin/index.js did the trick

`if(shouldExtract !== wasExtracted) {`
to
`if(shouldExtract && !wasExtracted) {`

issue in my case was that it was trying to recompile when shouldextract was false and wasExtracted was true

Also it looks like in my case, aside from having a named entry including same css as an async chunk, this issue was only happening for me when my webpack config had two instances of `new ExtractTextPlugin(...)` in the plugins[]

**Comment by hequ** [comment] 2017-02-28 08:20
I'm also having this problem, but in my case this `doesn't export content` error is happening in watch mode. Initially the compilation runs fine, but when I do a change to code the watch reload will fail with the error message. What is more interesting is that, when I do a second change, then everything compiles nicely again. So every second reload fails. Doing the fix, @dalimian proposed, fixed this error for me.

**Comment by Crazymax11** [comment] 2017-03-28 03:12
what's about PR merging?

**Closed** 2017-04-24 18:55 UTC
Labels: type: bug

**Comment by kostasmanionis** [comment] 2017-08-02 16:34
Is anyone still experiencing this with `3.0.0` ? @dalimian suggestion fixes the issue for me

**Comment by JulianJorgensen** [comment] 2017-09-13 03:44
@kostasmanionis yes still experiencing it. Only when I run rimraf (yarn clean) though. Still looking into it.
