### ISSUE TITLE
Webpack 2: How to extract CSS/LESS modules into CSS files?

### ISSUE THREAD

**Issue by hipertracker** [webpack-contrib/extract-text-webpack-plugin#250] opened 2016-09-20 00:17 UTC
I use Webpack2 and LESS modules. I'd like to extract them into CSS files.

It does NOT work:

```
// webpack.config.js
//...
module: {
  loaders: [
    //...
    test: /\.less$/,
    loader: ExtractTextPlugin.extract({
      fallbackLoader: 'style',
      loader: 'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!postcss!less'
    }),
  ]
}
```

I get `Module not found: Error: Can't resolve '[object Object]' ...` when I import style.css in my JS file.

But this works:

```
//...
module: {
  loaders: [
    //...
    test: /\.less$/,
    loader: 'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!postcss!less',
  ]
}
```

I am not sure how to use `extract-text-webpack-plugin` in Webpack 2 for CSS/LESS modules.

**Comment by cyberwombat** [comment] 2016-09-23 18:47
Posted same question on SO and managed to get it working. Check  [it out](http://stackoverflow.com/questions/39666983/webpack2-loading-and-extracting-less-file/39667618#39667618). Perhaps that will help.

**Comment by enzolutions** [comment] 2016-12-01 23:33
Hi @cyberwombat 

I tried what you mentioned but doesn't work. this is my webpack.config.js

```
var webpack = require("webpack");
var path = require('path');
var glob_entries = require('webpack-glob-entries');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var OmitTildeWebpackPlugin = require('omit-tilde-webpack-plugin');

var MODULE_BUILD_DIR = path.resolve(__dirname, 'web/assets/build');
var MODULE_BUILD_CSS_DIR = path.resolve(__dirname, 'web/assets/css');
var MODULE_APP_DIR = path.resolve(__dirname, 'client/');

  var plugins = [];

  plugins.push(
    new ExtractTextPlugin('styles/magicgen.css', {
        allChunks: true
    })
  );

  plugins.push(
    new OmitTildeWebpackPlugin({
        deprecate: false
    })
  );

var config = {
    plugins: getPlugins(),
    //It generates all the files in a folder as entries.
    entry: glob_entries('./client/**/*.register.jsx'),
    output: {
       path: MODULE_BUILD_DIR,
       filename: '[name].js'
    },
    module: {
        loaders: [
          { test: require.resolve("react"), loader: "expose?React" },
          { test: /\.css$/, include: MODULE_BUILD_CSS_DIR, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
          { test: /\.less$/, include: MODULE_APP_DIR,  loader: ExtractTextPlugin.extract({ loader:[ 'css', 'less'], fallbackLoader: 'style-loader' })},
          { test: /\.jsx?/, include: MODULE_APP_DIR, exclude: /node_modules/, loader: 'babel'}
        ]
    }
};

module.exports = config;
```

But I still get the following error, because is not able to process @import call in less files

```
ERROR in ./~/antd/lib/style/index.less
Module parse failed: /Users/enzo/www/MagicGen/node_modules/antd/lib/style/index.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/enzo/www/MagicGen/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/enzo/www/MagicGen/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/enzo/www/MagicGen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/enzo/www/MagicGen/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/antd/lib/row/style/index.js 3:0-33
```

Any ideas?

**Comment by felixsanz** [comment] 2016-12-28 05:28
bump, i have the same problem

**Comment by TNT-Likely** [comment] 2016-12-28 08:12
+1

**Comment by enzolutions** [comment] 2016-12-28 13:03
This trick resolve my problem

```
var webpack = require("webpack");
var path = require('path');
var glob_entries = require('webpack-glob-entries');
var OmitTildeWebpackPlugin = require('omit-tilde-webpack-plugin');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var extend = require("xtend");

var extractLESS = new ExtractTextPlugin('styles/[name].css',  {
    allChunks: true
});

var MODULE_BUILD_DIR = path.resolve(__dirname, 'web/assets/build');
var MODULE_BUILD_CSS_DIR = path.resolve(__dirname, 'client/css');
var MODULE_APP_DIR = path.resolve(__dirname, 'client/');

function getPlugins() {
    var plugins = [];

    plugins.push(extractLESS);


    plugins.push(
        new OmitTildeWebpackPlugin({
            deprecate: false
        })
    );

    return plugins;
}

var config = [
    {
        plugins: getPlugins(),
        entry: extend(glob_entries('./client/**/*.register.jsx'), glob_entries('./client/less/*.less')),
        output: {
            path: MODULE_BUILD_DIR,
            filename: '[name].js'
        },

        module: {
            loaders: [
                { test: require.resolve("react"), loader: "expose?React" },
                { test: /\.css$/, include: MODULE_BUILD_CSS_DIR, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
                { test: /\.less$/i, loader: extractLESS.extract(['css','less'])},
                { test: /\.jsx?/, include: MODULE_APP_DIR, exclude: /node_modules/, loader: 'babel'},
            ],
        }
    }
];

module.exports = config;
```

**Comment by KeithZhang** [comment] 2017-01-10 09:58
it works for me, "webpack": "2.2.0-rc.3" and "extract-text-webpack-plugin": "2.0.0-beta.4"

it's my webpack.config.babel.js:

```
module: {
    loaders: [
      {
        test: /\.less$/,
        loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: "css-loader!less-loader",
        })
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader?cacheDirectory'
      }
    ]
  }
```

but when i use an other code way, it doesn't work:
```
module: {
    rules: [
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: ["css-loader", "less-loader"],
        })
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader?cacheDirectory'
      }
    ]
  }
```

**Comment by selbekk** [comment] 2017-01-18 19:21
Thought I'd share mine as well, since I got it working.

Dependencies:

`webpack.config.js`:
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: './js/index.js',
    output: {
        filename: 'scripts.js',
        path: 'theme/resources',
    },
    module: {
        rules: [
            {
                test: /.js$/,
                use: [
                    { loader: 'babel-loader' }
                ],
            },
            {
                test: /.less$/,
                loader: ExtractTextPlugin.extract({
                        fallbackLoader: 'style-loader',
                        loader: "css-loader!less-loader",
                }),
            },
        ],
    },
    plugins: [
        new ExtractTextPlugin('styles.css'),
    ],
};

```

**Comment by rohmanhm** [comment] 2017-01-19 14:01
Help me, I got some problem.
after following your config, still I got `tahu.css` file doesn't generated.

this is my `webpack.config.js` file
```
var webpack = require('webpack')
var path = require('path')
var ExtractTextPlugin = require('extract-text-webpack-plugin')

var env = process.env.NODE_ENV
var config = {
  entry: path.join(__dirname, 'src/index.js'),
  resolve: {
    extensions: ['.js', '.jsx']
  },
  module: {
    rules: [
      {
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['react', ['es2015', { modules: false }], 'stage-0']
          }
        },
        resource: {
          exclude: /(node_modules|bower_components)/,
          test: /.jsx?$/
        }
      }, {
        resource: {
          test: /.scss?$/
        },
        use: {
          loader: ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: "css-loader!sass-loader",
          })
        }
      }
    ]
  }
}

switch (env) {
  case 'production':
    Object.assign(config, {
      output: {
        path: path.join(__dirname, 'build'),
        publicPath: 'build',
        filename: 'bundle.min.js'
      },
      devtool: false,
      plugins: [
        new webpack.DefinePlugin({
          'process.env.NODE_ENV': JSON.stringify('production'),
          '__DEVTOOLS__': false
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false,
            screw_ie8: true
          },
          mangle: false,
          comments: false
        })
      ]
    })
    break

  case 'development':

  default:
    Object.assign(config, {
      output: {
        path: path.join(__dirname, 'build'),
        publicPath: 'build',
        filename: 'bundle.js',
        chunkFilename: '[name].js'
      },
      devtool: 'inline-sourcemap',
      plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new ExtractTextPlugin('tahu.css')
      ],
      devServer: {
          contentBase: __dirname + '/'
      }
    })
    break
}

module.exports = Object.assign({}, config);

```

this is my dependencies

```
"devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-register": "^6.18.0",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "node-sass": "^4.3.0",
    "sass-loader": "^4.1.1",
    "style-loader": "^0.13.1",
    "webpack": "2.2.0-rc.7",
    "webpack-dev-server": "^1.16.2"
  },
```

**Comment by McGiogen** [comment] 2017-01-20 13:52
I share my working configuration: 
```
module.exports = {
    ...
    module: {
        rules: [
            {
                test: /\.css$/,
                exclude: path.resolve(__dirname, './src/app'),
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader', 'postcss-loader'],
                }),
            }, {
                test: /\.scss$/,
                exclude: path.resolve(__dirname, './src/app'),
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader', 'postcss-loader', 'sass-loader'],
                }),
            },
            ...
        ]
    }
}
```
Notice the use of `loader` instead of the webpack 2 attribute `use`. Probably the last one is still not supported by latest ExtractTextPlugin beta version. [This](https://github.com/webpack/extract-text-webpack-plugin/issues/265) is the related issue.

**Comment by rohmanhm** [comment] 2017-01-20 14:59
@McGiogen what version of your dependencies?

**Comment by McGiogen** [comment] 2017-01-20 15:06
@rohmanhm I've updated my previous response with package.json. (I'm working on it actually, this is why I'm using 'beta' instead of a specific version)

**Comment by rohmanhm** [comment] 2017-01-21 14:26
@McGiogen copied your config and still didn't work. Same version of dependencies, same config. BUT .. different result.

here's my dependencies.
```
"devDependencies": {
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "beta",
    "node-sass": "^4.3.0",
    "postcss-loader": "^1.2.2",
    "sass-loader": "^4.1.1",
    "style-loader": "^0.13.1",
    "webpack": "beta",
    "webpack-dev-server": "^1.16.2"
  },
```

**Comment by McGiogen** [comment] 2017-01-21 15:12
The only error I see is that also webpack-dev-server must be in beta, try to change
´´´
"webpack-dev-server": "^1.16.2"
´´´
to
´´´
"webpack-dev-server": "beta"
´´´

**Comment by rohmanhm** [comment] 2017-01-21 15:25
I think it doesn't make sense, because actually I didn't need this.

**Comment by McGiogen** [comment] 2017-01-21 16:07
Uhm... I saw you used [resolve.extensions](https://webpack.github.io/docs/configuration.html#resolve-extensions), this is a quote that I think could help you: *IMPORTANT: Setting this option will override the default, meaning that webpack will no longer try to resolve modules using the default extensions. If you want modules that were required with their extension (e.g. require('./somefile.ext')) to be properly resolved, you must include an empty string in your array.*

I think you should use
```
resolve: {
    extensions: ['.js', '.jsx', '']
},
```

**Comment by rohmanhm** [comment] 2017-01-21 16:51
When I add an empty string to `resolve.extensions` webpack throw a new error. 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[4] should not be empty.
```
=======================================================================

Ok let's move on.

I created a new config, without `resolve.extensions`
When I finish running, the result is just generate `test/lala.js` file, but `styles.css` not generated.

> nb: The `scss` file is on root directory `./style.scss`

This is my new webpack config file
```
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: './index.js',
    output: {
        filename: 'lala.js',
        path: 'test',
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader', 'postcss-loader'],
                }),
            }, {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader', 'postcss-loader', 'sass-loader'],
                }),
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('styles.css'),
    ],
};
```

I don't know What The Headache is going on all be do not work.

**Comment by McGiogen** [comment] 2017-01-21 17:06
You can try to change `new ExtractTextPlugin('styles.css')` to the new version of the constructor `new ExtractTextPlugin({ filename: 'styles.css' }),` (the one I use).

**Comment by rohmanhm** [comment] 2017-01-22 02:07
would you share you project with work configuration? I tried your suggestion but still do not work.

**Comment by McGiogen** [comment] 2017-01-23 08:18
This is my webpack.config.js: http://pastebin.com/mtJn4mFX
I'm sorry but it is not be perfect because I'm still on it (but it works) and some comments are in italian.

**Comment by rohmanhm** [comment] 2017-01-23 11:25
Thanks for sharing @McGiogen 

But I think it's too complicated. 😀

**Comment by rohmanhm** [comment] 2017-01-23 13:42
The question is, Should I require `[name].scss` file to entry file on webpack config like `index.js`? So webpack can recognize if `[name].scss` need some action.

**Comment by McGiogen** [comment] 2017-01-23 14:31
Sure, if you don't require()/import a file webpack don't put it in the build.

**Comment by rohmanhm** [comment] 2017-01-23 15:41
Thanks @McGiogen  for helping, 
my bad is forgot to require my `.scss` file. My case solved.

**Comment by scott-thrillist** [comment] 2017-01-30 07:44
@rohmanhm How exactly did you require your .scss file? I'm under the impression you don't have to do this if you use ExtractTextPlugin

**Comment by rohmanhm** [comment] 2017-01-30 11:48
@scott-thrillist I just write `require('path/to/file.scss')` to my `index.js`. How can I do that without requiring `.scss` file?

**Comment by scott-thrillist** [comment] 2017-01-30 15:46
@rohmanhm gotcha and thanks, I figured this out myself as well but it seems completely backwards to require a CSS/SASS entry point within a javascript import. I guess this is because webkit assumes you'll let it do it's thing with regards to letting it stick CSS wherever it seems necessary.

Wish the docs were more fleshed out on this!

**Comment by lmx99** [comment] 2017-02-09 12:43
i have found so many resolution, and this works fine !!!!!

         module: {
            rules: [{
                    test: /\.js$/,
                    use: [
                        'babel-loader',
                    ],
                    exclude: /(node_modules|bower_components)/,
                },

                {
                    test: /\.less$/,
                    loader: ExtractTextPlugin.extract({
                        fallbackLoader: "style-loader",
                        loader: "css-loader!less-loader",
                    }),
                }
           ],

        },

and the plugin shoud be like bellow

    new ExtractTextPlugin({ filename: '../../css/[name].css', disable: false, allChunks: true })

**Comment by blackcater** [comment] 2017-02-13 14:20
Try following code:

```javascript
export default {
  // ...
   module: {
      rules: [
         {
          test: /\.less$/,
          loader: ExtractTextPlugin.extract({
            fallback: 'style-loader',
           //`loader` option is no longer supported, using `use` option instead
            use: [ 
              {
                loader: 'css-loader',
                options: {
                  modules: true,
                  importLoaders: 1,
                  localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  plugins: () => [
                     // postcss plugins
                  ],
                },
              },
              {
                loader: 'less-loader',
                options: {
                  sourceMap: false,
                },
              },
            ],
          }),
        },
      ],
   plugins: [
     new ExtractTextPlugin({
        filename: 'css/app.[contenthash].css',
        disable: env === 'development',
        allChunks: true,
      }),
   ],
}
```

**Comment by zhuping** [comment] 2017-02-15 06:43
it's work for me, "webpack": "2.2.1" and "extract-text-webpack-plugin": "2.0.0-rc.3"

```js
module: {
  rules: [
    {
      test: /\.less$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'less-loader']
      })
    }
  ]
},
plugins: [
  new ExtractTextPlugin({
    filename: 'index.css',
    disable: false,
    allChunks: true
  })
]
```

**Comment by scottdj92** [comment] 2017-02-17 21:18
Considering that the documentation has been updated: [#413](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/413), can we close this one and similar issues?

**Comment by koutsenko** [comment] 2017-02-19 01:13
@zhuping it's not work for me, 
```
Error: Chunk.entry was removed. Use hasRuntime()
```

**Comment by jcasero** [comment] 2017-02-19 21:24
@koutsenko It's a known bug of the stable version. Take a look [here](https://github.com/webpack/webpack/issues/2764#issuecomment-277683820)

**Comment by eduardoinnorway** [comment] 2017-03-23 18:59
none of above worked for me. I just want to foo.less > foo.css in the same folder.

**Comment by michael-ciniawsky** [comment] 2017-04-22 13:10
Please try agan with webpack 2 / ETWP 2 && **less-loader v4.0.3** , if still regressions this seems to be an error with the resolver of `less-loader` feel free to reopen and maybe open an issue in `less-loader` aswell :)

**Closed by michael-ciniawsky** 2017-04-22 13:10 UTC
Labels: webpack-2

**Comment by huangweb** [comment] 2017-11-03 08:44
I have a same problem and I changed my code according to the above person said, but it still not work.
Finally, I changed
`new ExtractTextPlugin('bundle.css')`
to
`new ExtractTextPlugin({ 
           filename: 'bundle.css', 
           disable: false, 
           allChunks: true 
       }),
`
and it works.
