### ISSUE TITLE
Getting Error with Extract-Text-Webpack-Plugin

### ISSUE THREAD

**Issue by Moocow89** [webpack-contrib/extract-text-webpack-plugin#417] opened 2017-02-20 14:29 UTC
I am getting this error below:

![screen shot 2017-02-18 at 11 17 46 pm](https://cloud.githubusercontent.com/assets/17732223/23099375/f424991e-f632-11e6-930d-3ea20019b4d2.png)

But I am using the plugin in my config:

![screen shot 2017-02-18 at 2 11 41 pm](https://cloud.githubusercontent.com/assets/17732223/23099374/f4235842-f632-11e6-9f2f-66e5663b8aa5.png)

using the following versions: 
"extract-text-webpack-plugin": "^2.0.0-rc.3",
"webpack": "^2.2.1",

Here is my repo:

https://github.com/Moocow89/portfolio-website

**Comment by bebraw** [comment] 2017-02-20 14:47
Which commands are you running? Could you simplify the project and drop anything that's not needed to get the error?

**Comment by scottdj92** [comment] 2017-02-20 15:17
I cloned the repo, ran `npm start` and didn't receive any errors.

@Moocow89 Can you run `node -v` in your terminal and tell us what version of Node you're using? For my case, I was running `7.5.0`

**Comment by Moocow89** [comment] 2017-02-20 15:31
@scottdj92 I was running an old version on node so I updated it to 7.5.0 but am still getting the same error. I only get the error when I run "npm run build", running "npm start" does not give me the error.

**Comment by scottdj92** [comment] 2017-02-20 16:12
Ah, I see. I'm getting the same error. It looks like this project was cloned from Cory House's lesson on Pluralsight. Did you see in the video that he had it working?

It looks like line 50 causes it to throw an error. Removing `underscore-template-loader` fixes the error and makes the project run correctly.

**Comment by Moocow89** [comment] 2017-02-20 16:22
@scottdj92 I think that worked. Thank you very much. I did originally copy a lot of this from the Pluralsight course, but Cory doesn't use SCSS in the build so that's where I started running into problems.

**Comment by bebraw** [comment] 2017-02-20 16:37
Apparently this is related to https://github.com/webpack/webpack/pull/4189 . Once that gets merged, the original code might work. Worth a go after that.

**Comment by bebraw** [comment] 2017-03-05 13:58
The PR was merged. You could try running against webpack `master` to see if that fixes it.

**Comment by GeorgeKnap** [comment] 2017-03-23 08:15
The issue is still there in webpack 2.3.1. Guess the [webpack/webpack/#4189](https://github.com/webpack/webpack/pull/4189) did not help. 

```
"@ngtools/webpack": "1.2.14",
 "extract-text-webpack-plugin": "2.1.0",
"webpack": "2.3.1"
```

**Comment by jorawarsingh** [comment] 2017-03-28 15:42
same issue with all latest versions, any updates?

**Comment by jorawarsingh** [comment] 2017-03-28 16:44
#420

**Comment by patrikx3** [comment] 2017-03-28 16:46
yep, AOT is not mature, I keep it out, work on new functions :(

**Comment by d3viant0ne** [comment] 2017-03-28 17:04
@patrikx3  AOT works just fine. I have 6 applications running in prod, 4 on 2.x and 2 more running 4.0.0 all with scss & all published AOT. All running the same boilerplate with the particulars below.

```
"@ngtools/webpack": "^1.3.0",
"extract-text-webpack-plugin": "^2.1.0",
"webpack": "^2.3.1",
```

In every case I have seen referencing this issue, it's a configuration issue not a problem with the fix that went into Webpack.

@bebraw - This issue should be closed.

1.) It's based on rc.3 
2.) It was a configuration issue to begin with
3.) The rest of the issues referencing this one all boil down to configuration.

**Comment by bebraw** [comment] 2017-03-28 17:08
Ok, let's close. 👍

**Comment by patrikx3** [comment] 2017-03-28 17:08
For me I have no idea how it is not working with Angular Material.  
Can you send me your webpack config? 
I use only latest npm versions.

Besides AOT with JIT not working as well (I need to add in JIT as well and in v4 broken again, I need compiling JIT plus AOT at once). There are so many scenarios. I guess 6 applications all the same.

**Comment by patrikx3** [comment] 2017-03-28 17:08
Plus in JIT and Uglify it works, and in AOT not working. :) CIAO

**Closed by bebraw** 2017-03-28 17:08 UTC
Labels: bug, webpack-2

**Comment by d3viant0ne** [comment] 2017-03-28 17:10
@GeorgeKnap - I've looked at your issue in @angular.cli as well. If you can point me to some code, I can help you get this dialed in. Looks to be boilerplate + Angular + Material2 which is my day to day.

Hit me up on gitter if you want a hand.

**Comment by jorawarsingh** [comment] 2017-03-28 17:18
i am having the same issue after updating the version as well as you mentioned @d3viant0ne  here is my configuretion
```
{
    test: /\.css$/,
    include: path.resolve(process.cwd(), 'src', 'app'),
    use: ['to-string-loader', 'css-loader']
    },
    {
      test: /\.css/,
       exclude: [/node_modules/, /src\/app/],
       use: ExtractTextPlugin.extract({
       fallback: 'style-loader',
      use: ['css-loader','to-string-loader']
   })
}
```
and plugin
`new ExtractTextPlugin({filename:'style.css'})`
and now error

> (node:5400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Child compilation failed:
> Module parse failed: D:\www\AnnualReportWeb\node_modules\@angular\material\list\list.css Unexpected token (1:0)
