### ISSUE TITLE
feat: DeprecationWarning: Chunk.modules in Webpack 3.x

### ISSUE THREAD

**Issue by tleunen** [webpack-contrib/extract-text-webpack-plugin#529] opened 2017-06-07 22:44 UTC
Webpack 3.0-rc was released and this plugin currently doesn't support it.

I haven't tested it, it might be just a question of updating the peerDependency.

**Comment by michael-ciniawsky** [comment] 2017-06-07 22:56
It doesn't work at all or does it just displays a warning for an unmet peerDepedency?

**Comment by gdub22** [comment] 2017-06-08 21:22
It's working with webpack 3.0.  It does emit this warning however:

```
DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /node_modules/extract-text-webpack-plugin/index.js:271:24
```

**Comment by MirrorBytes** [comment] 2017-06-09 03:21
Change line 271 to this:
`async.forEach(Array.from(chunk.mapModules(function(c) { return c; })), function(module, callback) {`

It solved the issue for me (ran 3 tests, might need a bit more testing). The Array.from() is specifically to counter an issue I have had in the past with several linux distros not liking "array-like" structures (such as arrays built from mapping).

**Comment by MirrorBytes** [comment] 2017-06-09 19:47
@d3viant0ne Should a put a pull request in? It's not exactly urgent, but this is the most resource independent way to adapt to avoid this warning and making it work more effectively for Webpack 3.

**Comment by michael-ciniawsky** [comment] 2017-06-09 20:19
Yes feel free to send PR :) for discussion && finishing details

**Comment by d3viant0ne** [comment] 2017-06-10 23:44
Everyone - The change throwing the deprecation warning looks like it isn't going to be backwards compatible. ( need to verify this, i'm just looking at code atm ).

This is going to have to go out as a `semver: Major` which means everyone is going to have to live with the deprecation warning for a bit. I've put this in the `3.0.0 milestone`

**Comment by d3viant0ne** [comment] 2017-06-10 23:49
> The Array.from() is specifically to counter an issue I have had in the past with several linux distros not liking "array-like" structures (such as arrays built from mapping)

@MirrorBytes I remember this being an older NodeJS issue that cropped up in Fedora for me iirc. It's also something I haven't seen in quite a while and don't believe it to be a relevant issue for our supported `engines: ` range.

If you know of an instance where that isn't the case, I'll configure the applicable vm to verify the need for `Array.from()`

**Comment by d3viant0ne** [comment] 2017-06-11 00:56
@MirrorBytes - If you want to PR in the changes for the deprecation warnings, you need to target this branch .... https://github.com/webpack-contrib/extract-text-webpack-plugin/tree/feature/webpack3

**Comment by MirrorBytes** [comment] 2017-06-13 03:31
Sorry for the delay. I removed Array.from() and submitted a pull request for Webpack-3 branch.

**Comment by irowbin** [comment] 2017-06-25 15:32
Well i am having the same issue here.
```javascript
(node:4692) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumber OfModules/mapModules/forEachModule/containsModule instead
```
The package.json file
```javascript
{
  "name": "app",
  "version": "1.0.0",
  "description": "app",
  "scripts": {
    "start": "webpack-dev-server --hot --inline --progress --colors  --port 2000"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "~4.2.4",
    "@angular/common": "~4.2.4",
    "@angular/compiler": "~4.2.4",
    "@angular/core": "~4.2.4",
    "@angular/forms": "~4.2.4",
    "@angular/http": "~4.2.4",
    "@angular/material": "~2.0.0-beta.7",
    "@angular/platform-browser": "~4.2.4",
    "@angular/platform-browser-dynamic": "~4.2.4",
    "@angular/router": "~4.2.4",
    "core-js": "~2.4.1",
    "rxjs": "~5.4.1",
    "zone.js": "~0.8.12"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.2.4",
    "@angular/platform-server": "~4.2.4",
    "@ngtools/webpack": "~1.4.1",
    "@types/jquery": "^2.0.43",
    "@types/node": "~8.0.0",
    "@types/typeahead": "~0.11.29",
    "angular2-router-loader": "~0.3.5",
    "angular2-template-loader": "~0.6.2",
    "awesome-typescript-loader": "~3.1.3",
    "chunk-manifest-webpack2-plugin": "~1.0.1",
    "compression-webpack-plugin": "~0.4.0",
    "css-loader": "~0.14.0",
    "extract-text-webpack-plugin": "^3.0.0-beta.3",
    "file-loader": "~0.11.2",
    "html-loader": "~0.4.5",
    "html-webpack-plugin": "~2.28.0",
    "imports-loader": "^0.7.1",
    "moment": "^2.18.1",
    "null-loader": "~0.1.1",
    "raw-loader": "~0.5.1",
    "rimraf": "~2.6.1",
    "style-loader": "~0.18.2",
    "tslint": "~5.4.3",
    "typescript": "~2.3.4",
    "uglify-js": "^3.0.19",
    "uglify-loader": "~2.0.0",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "webpack": "~3.0.0",
    "webpack-bundle-analyzer": "~2.8.2",
    "webpack-chunk-hash": "~0.4.0",
    "webpack-dev-server": "~2.5.0",
    "webpack-merge": "~4.1.0",
    "webpack-uglify-parallel": "~0.1.3"
  }
}
```
ran this cmd `webpack-dev-server --hot --inline --progress --colors  --port 2000`

and i got this 
![kdjtj](https://user-images.githubusercontent.com/13050078/27517384-5da1db88-59eb-11e7-97b2-2ac85e2f54f2.png) says compiled successfully with warning but when i run the app, the error appeared.
![rjekh](https://user-images.githubusercontent.com/13050078/27517395-88286a02-59eb-11e7-8b0d-d8aa6a44dc9d.png)

**Comment by hdfs010** [comment] 2017-06-27 07:44
(node:19215) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

just to modify
 
node_modules/_extract-text-webpack-plugin@2.1.2@extract-text-webpack-plugin/index.js:
   34  	} else if(checkedChunks.indexOf(chunk) < 0) {
   35  		checkedChunks.push(chunk);
   36: 		**chunk.modules**.slice().forEach(function(module) {
   37  			intoChunk.addModule(module);
   38  			module.addChunk(intoChunk);

**Comment by d3viant0ne** [comment] 2017-06-29 20:22
This is a known issue & already has a PR to resolve it. It's a Major so you will have to use the etwp `3.x` major release.

See #540 for the particulars

**Comment by d3viant0ne** [comment] 2017-07-07 16:46
This is resolved as of `extract-text-webpack-plugin@3.0.0-rc.1` ( requires Webpack 3.1.0 )

**Comment by irowbin** [comment] 2017-07-07 17:25
@d3viant0ne I've just checked with latest version but got no luck yet. No idea what breaks again. Here is my package.json
```javascript
{
  "description": "app",
  "scripts": {
    "start": "webpack-dev-server --hot --inline --progress --colors --port 8082"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.2.5",
    "@angular/compiler": "~4.2.5",
    "@angular/core": "~4.2.5",
    "@angular/forms": "~4.2.5",
    "@angular/http": "~4.2.5",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "~4.2.5",
    "@angular/platform-browser-dynamic": "~4.2.5",
    "@angular/router": "~4.2.5",
    "core-js": "~2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/animations": "~4.2.5",
    "@angular/compiler-cli": "^4.2.5",
    "@angular/platform-server": "^4.2.5",
    "@ngtools/webpack": "~1.5.0",
    "@types/jquery": "^2.0.48",
    "@types/node": "~8.0.8",
    "angular2-router-loader": "~0.3.5",
    "angular2-template-loader": "~0.6.2",
    "awesome-typescript-loader": "~3.2.1",
    "bootstrap": "^3.3.7",
    "compression-webpack-plugin": "^0.4.0",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^3.0.0-rc.1",
    "file-loader": "^0.11.2",
    "hammerjs": "~2.0.8",
    "html-loader": "~0.4.5",
    "html-webpack-plugin": "^2.29.0",
    "jquery": "~2.2.4",
    "null-loader": "^0.1.1",
    "raw-loader": "~0.5.1",
    "rimraf": "~2.6.1",
    "style-loader": "~0.16.1",
    "tslint": "~5.5.0",
    "typescript": "~2.4.1",
    "uglify-js": "^3.0.23",
    "uglify-loader": "~2.0.0",
    "webpack": "~3.1.0",
    "webpack-dev-server": "~2.5.1",
    "webpack-merge": "~4.1.0"
  }
}
```
ran this cmd from npm `npm cache clean --force && npm cache clear --force && rimraf node_modules && npm i
`
then i got this

![capture](https://user-images.githubusercontent.com/13050078/27969048-182bf124-6369-11e7-8fbc-a71878883876.PNG)

and error on the browser console

![capture1](https://user-images.githubusercontent.com/13050078/27969064-2df0e7e4-6369-11e7-9249-191897be0c57.PNG)
Am i missing something here?

**Comment by michael-ciniawsky** [comment] 2017-07-07 17:34
@irowbin Where is the deprectation warning ? 🙃  `reflect-metdata` shim seems to be unrelated to ETWP

**Comment by irowbin** [comment] 2017-07-07 17:42
@michael-ciniawsky  Well, the same config in `webpack v2.6.1`  with `extract-text-webpack-plugin v2.1.2` works just fine.  The latest version got something to do with this issue. Even i am not getting the chunk information on the console. Compiled successfully... that's all i got and app just stuck. 🙃

**Comment by michael-ciniawsky** [comment] 2017-07-07 18:15
@irowbin Then we misunderstood each another here :). Please try without `extract-text-weboack-plugin` to confirm it isn't another issue with your current setup migrating from `webpack v2.0.0...3.0.0` and if it isn't, please open a new issue. The issue here is tracking the `chunk.modules` deprecation warnings :stuck_out_tongue:

**Comment by d3viant0ne** [comment] 2017-07-07 18:37
The reflect shim has nothing to do with etwp.

**Comment by d3viant0ne** [comment] 2017-07-07 18:44
Closed by be7936df6b947788f6294864ebfa67c95a0cf06b

**Closed by d3viant0ne** 2017-07-07 18:44 UTC
Labels: flag: Has pull request, priority: 2 (urgent), semver: Major, severity: 3 (broken), type: Bug

**Comment by irowbin** [comment] 2017-07-08 04:09
Well, thanks @d3viant0ne & @michael-ciniawsky The warning is gone and app works just fine.

**Comment by ova2** [comment] 2017-07-12 22:58
@d3viant0ne I still have the warning

"DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead."

My package.json: https://github.com/ova2/angular-development-with-primeng/blob/master/angular-primeng-seed-for-authors/package.json

Simple try to execute `npm run start:prod`

**Comment by irowbin** [comment] 2017-07-13 02:56
@ova2  Please update to latest `webpack v3.2.0` & `extract-text-webpack-plugin v3.0` before updates, Clean old dependency from global and project.

**Comment by ova2** [comment] 2017-07-13 06:50
@irowbin I already have `webpack v3.2.0` & `extract-text-webpack-plugin v3.0` and no old deps. The warning is still here. See this comment as well: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/561#issuecomment-314927477 There is still one (or more?) place(s) in the plugin which are not fixed yet.

**Comment by irowbin** [comment] 2017-07-13 07:07
@ova2 Its wired that author himself having this deprecation warning 🤣 . Mine works fine after i did some cleanup and re-install. I was seeing this error till the `beta` stage but not after `rc`

**node**
`v6.11.0`

**npm**
`v5.2.0`

**webpack**
`v3.2.0`

**extract-text-webpack-plugin**
`v3.0`

**Comment by Igor-Vuk** [comment] 2017-07-13 22:47
I updated to webpack 3.2.0 and extract-text-webpack-plugin 3.0.0 deleted and installed node_modules again and I still get this warning.

**Comment by cebor** [comment] 2017-07-14 08:20
Cannot reproduce this, all works fine with `3.0.0`.

**Comment by Igor-Vuk** [comment] 2017-07-14 10:59
Tried it . Unfortunately I am sill getting the message.

**Comment by weaverryan** [comment] 2017-07-15 19:25
FYI - if you use webpack-chunk-hash (or webpack-md5-hash), the deprecation warning may be coming from it: https://github.com/alexindigo/webpack-chunk-hash/pull/9

**Comment by michael-ciniawsky** [comment] 2017-07-15 19:55
@Igor-Vuk @ova2 Could you both please share your `webpack.config.js` ? After some debugging I'm 99,9% sure the deprecation warning isn't coming from `extract-text-webpack-plugin`, in case you only get the useless `(node: 1234) DeprectationWarning: Chunk.modules is deprecated ...`  message use this to get a `stackTrace`

**WarningsPlugin.js**
```js
class WarningsPlugin {
  constructor (options = {}) {
    this.options = options
  }

  apply(compiler) {
    compiler.plugin('this-compilation', (compilation, cb) => {
      process.on('warning', (warning) => {
        console.warn('\n⚠️  Warnings Plugin\n\n')
        console.warn(`${warning.name}\n`)
        console.warn(`${warning.message}\n`)
        console.warn(`${warning.stack)\n`)
      });
    })
  }
}
```


### Before 

```
(node:14759) DeprecationWarning: Chunk.modules is deprecated. 
Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
```

### After 

```bash
⚠️ Warnings Plugin


DeprecationWarning

Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

    at NamedChunksPlugin.env.production.NamedChunksPlugin [as nameResolver] (.../.webpack/plugins.js:17:19)
    at chunks.forEach (.../node_modules/webpack/lib/NamedChunksPlugin.js:22:23)
    at Array.forEach (native)
    at Compilation.compilation.plugin (.../node_modules/webpack/lib/NamedChunksPlugin.js:20:12)
    at Compilation.applyPlugins1 (.../node_modules/tapable/lib/Tapable.js:75:14)
    at sealPart2 (.../node_modules/webpack/lib/Compilation.js:606:9)
    at Compilation.applyPluginsAsyncSeries (.../node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (.../node_modules/webpack/lib/Compilation.js:579:8)
    at applyPluginsParallel.err (.../node_modules/webpack/lib/Compiler.js:514:17)
    at .../node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (.../node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (.../node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

**Comment by ova2** [comment] 2017-07-15 20:41
@weaverryan Thanks a lot! The warning came from webpack-md5-hash. I've removed this plugin and the warning is gone. No issues more.

**Comment by Igor-Vuk** [comment] 2017-07-15 20:50
@weaverryan @michael-ciniawsky @ova2 
Yes. My warning was also comming from webpack-md5-hash. After uninstall it is ok. Does anyone have solution how to continue use it? We should probaby open an issue on webpack-md5-hash site.

**Comment by ova2** [comment] 2017-07-15 20:52
@Igor-Vuk I don't know why I was using it. I've realized I can live without this plugin - the Webpack generated hashes are fine.

**Comment by Igor-Vuk** [comment] 2017-07-15 20:57
@ova2 
Mine our not, for example vendor chunkhash changes when I make a new build even though just a bundle hash should change. With md5 is ok.

**Comment by ova2** [comment] 2017-07-15 21:19
@Igor-Vuk I use manifest and manifest.js file + Webpack records

// See https://medium.com/webpack/harnessing-the-power-of-webpack-2cd0e20ff1bf#.q9do1u54o
recordsPath: path.join(ROOT, 'config', 'webpack-records.json')

The hash of polyfill is fine after rebuild (I don't have a vendor file because it is merged together with main file due to better tree shaking).

**Comment by michael-ciniawsky** [comment] 2017-07-15 22:31
https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31

```diff
const { NamedChunksPlugin, NamedModulesPlugin } = require('webpack')
...
[
    new NamedModulesPlugin(),
    new NamedChunksPlugin((chunk) => {
      if (chunk.name) return chunk.name

      return chunk
-       .modules.map(({ context, request }) => path.relative(context, request)
+       .mapModules(({ context, request }) => path.relative(context, request)) // <= webpack >= 3
        .join('_')
    }),
    new CommonsChunkPlugin({
      name: [ 'vendor', 'runtime' ],
      minChunks: Infinity
    }),
    ...ExtractTextPlugin, ModuleConcatenationPlugin
]
```

Third-party Plugins are not needed most of the time imho :)

**Comment by d3viant0ne** [comment] 2017-07-16 08:23
I personally use md5-hash but I have a rather complex nginx setup related to what is & is not cached and for how long.

Outside of situations where your operational requirements warrant the added complexity, @michael-ciniawsky is right, you really don't need it.

**Comment by ayepRahman** [comment] 2017-07-17 15:28
guys how do you find and remove  webpack-md5-hash in my webpack

**Comment by d3viant0ne** [comment] 2017-07-17 17:39
@ayepRahman - Should be listed in your project devDependencies. If you don't see it there, it's a dependency of a dependency.

That said, if you are using someone's boilerplate project, removing that lib is likely going to break your production build.

**Comment by mahcr** [comment] 2017-07-28 22:00
I'm still getting the warning. 
```
"webpack": "^3.4.1",
"extract-text-webpack-plugin": "^3.0.0"
```

**Comment by d3viant0ne** [comment] 2017-07-28 22:50
This is not from `extract-text-webpack-plugin`

**Comment by oguzhanabali** [comment] 2017-08-05 14:52
I'm still getting the warning.

**Comment by d3viant0ne** [comment] 2017-08-05 23:26
@oguzhanabali  Read the comment directly above yours. The warning will be emitted by any plugin using the now deprecated `Chunk.modules` when trying to upgrade to `webpack@3.x`
